import { categoryGuidance, articleExtensions } from './content/catalogue.mjs';
import { floatingContact } from './content/floating-contact.mjs';
import { comparisonTable, sourceLinks, sourcesWithScope, applicationContent } from './content/technical-render.mjs';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { productProcurement } from './content/product-procurement.mjs';
import { productIdentity, procurementSections, productFaq } from './content/product-page.mjs';
import { specificationSection } from './content/specification-table.mjs';
import { phosphateDetails, phosphateSelection } from './content/phosphate-details.mjs';
import { products } from './content/products.mjs';
import { phosphateFamilies } from './content/phosphates.mjs';
import { articles } from './content/articles.mjs';
import { brand } from './content/brand.mjs';
import { isSelectionGuide } from './content/product-scope.mjs';
import { primaryNavigation, footerNavigation } from './content/navigation.mjs';
import { applicationItems, applicationGoals, inquiryUrl, applicationInquiry, productApplications, relatedProductSlugs, articleInquiry, relatedArticles, returnRoutes } from './content/journeys.mjs';
import { supplyPages, documentRequestUrl } from './content/supply-pages.mjs';

const root = path.dirname(fileURLToPath(import.meta.url));
const e = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const write = (relative, content) => { const target=path.join(root,relative); fs.mkdirSync(path.dirname(target),{recursive:true}); fs.writeFileSync(target,content.replace('<body>', '<body id="top">').replace('</body>',floatingContact()+'</body>'),'utf8'); };
// Keep the hand-authored error page while sharing the contact component.
const errorPage = fs.readFileSync(path.join(root,'404.html'),'utf8').replace(/<!-- floating-contact:start -->[\s\S]*?<!-- floating-contact:end -->/g,'');
write('404.html',errorPage);
const productLink = (slug, label, prefix='../') => {
  const product=products.find(item=>item.slug===slug);
  if(!product)throw new Error(`Unknown ingredient link: ${slug}`);
  return `<a href="${prefix}products/${e(slug)}.html">${e(label)}${isSelectionGuide(product)?' (selection guide)':''} <span aria-hidden="true">↗</span></a>`;
};

// The homepage uses the same identity and contact source as generated inner pages.
const homeValues={...brand,addressHtml:brand.addressLines.map(e).join('<br>'),navigationHtml:primaryNavigation(),footerNavigationHtml:footerNavigation()};
const home=fs.readFileSync(path.join(root,'content/home.template'),'utf8').replace(/\{\{(\w+)\}\}/g,(_match,key)=>{
  if(!(key in homeValues))throw new Error(`Unknown homepage content field: ${key}`);
  return ['heroHeadline','addressHtml','navigationHtml','footerNavigationHtml'].includes(key)?homeValues[key]:e(homeValues[key]);
});
write('index.html',home);

function shell({title,description,active,body}) {
  const navHtml=primaryNavigation('../',active);
  const pageTitle=`${title} | IngredientCore`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="theme-color" content="#173B4D"><meta name="description" content="${e(description)}"><title>${e(pageTitle)}</title><meta property="og:type" content="website"><meta property="og:site_name" content="IngredientCore"><meta property="og:title" content="${e(pageTitle)}"><meta property="og:description" content="${e(description)}"><link rel="icon" type="image/svg+xml" href="../assets/img/mark.svg"><link rel="stylesheet" href="../assets/css/style.css"><link rel="stylesheet" href="../assets/css/pages.css"></head>
<body><a class="skip-link" href="#main">Skip to content</a><div class="topline"><div class="container topline__inner"><span>${e(brand.identity)}</span><a href="mailto:${e(brand.email)}">${e(brand.email)} <span aria-hidden="true">↗</span></a></div></div>
<header class="site-header"><div class="container site-header__inner"><a class="brand" href="../index.html" aria-label="IngredientCore, home"><img src="../assets/img/logo.svg" width="285" height="48" alt="IngredientCore"></a><button class="menu-toggle" type="button" aria-controls="primary-navigation" aria-expanded="false" aria-label="Open navigation" data-menu-toggle><span></span><span></span><span></span></button><nav class="site-nav" id="primary-navigation" aria-label="Main navigation" data-menu>${navHtml}</nav></div></header>
<main id="main" tabindex="-1">${body}</main>
<footer class="site-footer"><div class="container footer__top"><div class="footer__brand"><img src="../assets/img/logo.svg" width="260" height="44" alt="IngredientCore"><p>${e(brand.focus)}</p></div>${footerNavigation('../')}<div class="footer__contact"><h3>Contact</h3><a href="mailto:${e(brand.email)}">${e(brand.email)}</a><a href="tel:${e(brand.phone)}">${e(brand.phoneDisplay)}</a><address>${brand.addressLines.map(e).join('<br>')}</address></div></div><div class="container footer__bottom"><span>© <span data-year>2026</span> IngredientCore. A subsidiary of Bespring Chemical.</span><span>English · Food ingredients</span></div></footer><script src="../assets/js/site.js" defer></script></body></html>`;
}

function banner(kicker,title,lead,crumb='') {
  const parts=crumb.split(' / ');
  const trail=crumb?`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Home</a>${parts.map((part,index)=>`<span aria-hidden="true"> / </span>${index===parts.length-1?`<span aria-current="page">${part}</span>`:part}`).join('')}</nav>`:'';
  return `<section class="page-hero"><div class="container"><div class="page-hero__top"><span class="section-kicker section-kicker--light"><span class="section-kicker__line"></span>${e(kicker)}</span>${trail}</div><h1>${title}</h1><p>${e(lead)}</p><div class="page-hero__pattern" aria-hidden="true"><span></span><span></span><span></span></div></div></section>`;
}

function sectionHead(kicker,title,lead=''){return `<div class="section-head page-section-head"><div><div class="section-kicker"><span class="section-kicker__line"></span>${e(kicker)}</div><h2>${title}</h2></div>${lead?`<p>${e(lead)}</p>`:''}</div>`;}
function cta(title,lead,button='Prepare inquiry',href='../contact/index.html'){return `<section class="page-cta"><div class="container page-cta__inner"><div><span class="section-kicker section-kicker--light"><span class="section-kicker__line"></span> NEXT STEP</span><h2>${title}</h2><p>${e(lead)}</p></div><a class="button button--cream" data-context-inquiry href="${e(href)}">${e(button)} <span aria-hidden="true">↗</span></a></div></section>`;}

const families=[
  ...phosphateFamilies,
  ['Preservation','Propionate and sorbate options for suitable shelf-life systems.'],
  ['Texture & stability','Hydrocolloids for viscosity, suspension and texture.'],
  ['Acidity control','Technical selection guides to acidulants and citrates for pH and flavor balance.'],
  ['Emulsification','A technical selection guide to bakery emulsifier functions.']
];
let productCards='';
for(const [family,summary] of families){
  const items=products.filter(item=>item.family===family);
  if(items.some(item=>isSelectionGuide(item)!==isSelectionGuide(items[0])))throw new Error('Mixed scope in family '+family);
  const additional=isSelectionGuide(items[0]);
  if(family===phosphateFamilies[0][0])productCards+='<div data-catalog-group id="food-phosphates">'+sectionHead('CORE INQUIRY FOCUS','Core ingredient families.','Phosphates, propionates, sorbates, sodium CMC and hydrocolloids are our initial focus. Each named ingredient is a starting point for discussing the exact material and proposed supply.');
  if(family==='Acidity control')productCards+='</div><div data-catalog-group>'+sectionHead('TECHNICAL COMPARISONS','Additional selection guides.','These pages explain related ingredients and qualification questions. They are educational guides, not an offer of supply from IngredientCore.');
  productCards+=`<section class="catalog-family" tabindex="-1" id="${family.toLowerCase().replace(/[^a-z0-9]+/g,'-')}"><div class="catalog-family__head"><div><span class="catalog-family__count">${additional?'SELECTION GUIDES':'CORE FAMILY'} / ${e(family.toUpperCase())}</span><h2>${e(family)}</h2><p>${e(summary)}</p>${categoryGuidance[family]?`<p class="catalog-family__guidance">${e(categoryGuidance[family])}</p>`:''}</div><span>${items.length} INGREDIENT GUIDES</span></div><div class="catalog-grid">${items.map(item=>`<a class="catalog-card" href="${e(item.slug)}.html" data-product-card data-search="${e(`${item.name} ${item.abbr} ${item.family} ${productProcurement(item).aliases.join(' ')}`.toLowerCase())}" data-family="${e(item.family)}" data-abbreviation="${e(item.abbr)}"><span class="catalog-card__top"><span>${e(item.abbr)}</span><span aria-hidden="true">↗</span></span><h3>${e(item.name)}</h3><p>${e(item.lead)}</p><span class="catalog-card__read">${additional?'Read selection guide':'View product & grade details'} <span aria-hidden="true">→</span></span></a>`).join('')}</div></section>`;
}
productCards+='</div>';
write('products/index.html',shell({title:'Phosphate Catalogue & Food Ingredient Guides',description:'Browse sodium, potassium and calcium phosphates, phosphate blends and other phosphate types, plus preservatives and hydrocolloids. Compare identities and grades.',active:'Products',body:
  banner('INGREDIENT FOCUS & GUIDES','Find your ingredient.<br><em>Compare the right form.</em>','Explore our core ingredient families, compare functions and tell us which grade or application you need.','Products')+
  `<section class="page-section catalog-intro"><div class="container"><div class="catalog-intro__grid"><div><div class="section-kicker"><span class="section-kicker__line"></span> DEFINE THE REQUIREMENT</div><h2>Start with a function.<br><span class="serif-accent">Then specify the grade.</span></h2></div><div><p>Compare ingredient functions and selection criteria, then contact us with your required material, grade, destination market and documents.</p><label class="catalog-search"><span aria-hidden="true">⌕</span><span class="sr-only">Search ingredient guides</span><input type="search" placeholder="Search names, abbreviations or synonyms" autocomplete="off" disabled data-product-search></label><label class="catalog-filter">Filter by family<select data-product-family disabled><option value="">All families</option>${families.map(([name])=>`<option value="${e(name)}">${e(name)}</option>`).join('')}</select></label><p class="catalog-search-help">Try STPP, monosodium phosphate, or anhydrous DCP. Search and family filter work together.</p><button type="button" class="search-clear" data-search-clear hidden>Clear search & filter</button><noscript><p>Search and filtering need JavaScript. Use the family links below; every product remains available.</p></noscript><p class="catalog-search__status" aria-live="polite" data-search-status>${products.length} ingredient guides shown</p></div></div><nav class="family-links" aria-label="Ingredient guide families"><span class="catalog-nav-label">Browse a family</span>${families.map(([name])=>`<a data-catalog-category href="#${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${e(name)} (${products.filter(p=>p.family===name).length})${['Acidity control','Emulsification'].includes(name)?' / Guides':''}</a>`).join('')}</nav>${productCards}<p class="catalog-empty" data-search-empty hidden>No matching guides. Clear the search and family filter above, <a href="../applications/index.html">browse food applications</a> or <a href="../contact/index.html">prepare an application brief</a>.</p></div></section>`+
  cta('Specify the ingredient you need.','Include the product or target function, food application, destination market, grade requirements and documents.','Prepare an ingredient brief')}));

for(const item of products){
  const detail=phosphateDetails[item.slug];
  const related=(detail?detail.related:relatedProductSlugs(item.slug)).map(slug=>products.find(p=>p.slug===slug));
  const relevantApps=productApplications(item.slug);
  const guide=isSelectionGuide(item);
  const productInquiry=inquiryUrl({intent:guide?'comparison':'product',ingredient:item.name,from:'product:'+item.slug});
  const directArticles=articles.filter(article=>article.products.includes(item.slug));
  const productReadings=detail?detail.readings.map(slug=>articles.find(a=>a.slug===slug)):(directArticles.length?directArticles:[articles.find(article=>article.slug==='qualify-ingredient-source')]).slice(0,2);
  const specificationInquiry=inquiryUrl({intent:'documents',ingredient:item.name,documents:'Current product specification for the proposed grade and source, including test methods; confirm availability',purpose:'Product selection and quotation',from:'product:'+item.slug});
  const displayName=item.name===item.abbr?e(item.name):`${e(item.name)} <em>${e(item.abbr)}</em>`;
  const productAction=guide?'Ask about selection':'Prepare product inquiry';
  const scopeText=detail?'Tell us the material form, food or process, destination market and required quantity. We can discuss your inquiry on that specific basis.':guide?'Technical selection guide for comparing ingredient functions and grades; it is not an offer of supply.':'Our focus includes this ingredient family. Tell us your required grade, food application and destination market to discuss the product and supporting records.';
  const body=banner((guide?'SELECTION GUIDE / ':'')+item.family.toUpperCase(),displayName,item.lead,`<a href="index.html">Products</a> / <a href="index.html#${item.family.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">${e(item.family)}</a> / ${e(item.name)}`)+
  `<section class="product-overview page-section"><div class="container product-overview__grid"><div><div class="section-kicker"><span class="section-kicker__line"></span> INGREDIENT OVERVIEW</div><h2>${detail?e(item.abbr)+': product profile':'What this ingredient<br><span class="serif-accent">can help you explore.</span>'}</h2>${productIdentity(item,e)}<p class="product-overview__lead">${e(detail?detail.introduction:item.role)}</p><a class="button button--navy" data-context-inquiry href="${e(productInquiry)}">${productAction} <span aria-hidden="true">↗</span></a>${detail?`<p class="product-specification-link"><a data-context-inquiry href="${e(specificationInquiry)}">Request specification <span aria-hidden="true">↗</span></a></p>`:''}</div><aside class="product-facts"><span class="product-facts__eyebrow">PROCUREMENT SNAPSHOT</span><dl><div><dt>Ingredient</dt><dd>${e(item.name)}</dd></div><div><dt>Also known as</dt><dd>${e(item.abbr)}</dd></div><div><dt>Ingredient family</dt><dd>${e(item.family)}</dd></div><div><dt>Grade & source</dt><dd>Confirm with current offer</dd></div></dl><p class="product-scope-note">${e(scopeText)}</p></aside></div></section>`+
  `<section class="product-section page-section page-section--tint"><div class="container">${sectionHead('APPLICATION SCREENING','Where it may <span class="serif-accent">fit.</span>','These are technical starting points, not finished-product performance or use authorizations.')}<div class="product-three">${item.uses.map((use,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><p>${e(use)}</p></article>`).join('')}</div></div></section>`+
  (detail?phosphateSelection(item,e):`<section class="product-section page-section"><div class="container product-checks"><div>${sectionHead('QUALIFICATION','Questions worth asking<br><span class="serif-accent">before approval.</span>')}<div class="product-question"><span>START HERE</span><p>${e(item.question)}</p></div></div><div><ol>${item.checks.map((check,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><p>${e(check)}</p></li>`).join('')}</ol></div></div></section>`)+
  specificationSection(item,e)+procurementSections(item,e,sectionHead)+productFaq(item,e,sectionHead)+
  `<section class="docs-strip"><div class="container docs-strip__grid"><div><span class="section-kicker section-kicker--light"><span class="section-kicker__line"></span> DOCUMENT REQUEST</span><h2>Request documents for <em>${e(item.abbr)}.</em></h2><p>${detail?`Tell us the material form, intended use, destination market and document purpose. Request ${e(productProcurement(item).documents.replace(/; confirm availability$/,''))}. Records depend on the proposed grade and source; any certificate applies only within its stated entity, site and product scope.`:`State the grade, source if known, food application, destination market and purpose. Ask about ${e(productProcurement(item).documents)}. Availability and permission to share must be confirmed for the proposed supply. Certificates must match their own entity, site and scope.`}</p></div><div class="docs-strip__actions"><a data-context-inquiry href="${e(documentRequestUrl({ingredient:item.name,from:'product:'+item.slug,documents:productProcurement(item).documents}))}">Request product documents <span aria-hidden="true">↗</span></a><a href="../quality/index.html#documents">Understand the records <span aria-hidden="true">↗</span></a></div></div></section>`+
  `<section class="related page-section"><div class="container"><p class="catalog-return"><a href="index.html#${item.family.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">Back to ${e(item.family)}</a></p>${related.length?sectionHead('COMPARE THE REQUIREMENTS','Related ingredient candidates.')+`<div class="related-grid">${related.map(r=>productLink(r.slug,r.name,'../')).join('')}</div>`:''}${relevantApps.length?`<div class="product-reading"><h3>Review the food application</h3>${relevantApps.map(app=>`<a href="../applications/index.html#${e(app.id)}">${e(app.name)} application questions <span aria-hidden="true">↗</span></a>`).join('')}</div>`:''}${productReadings.length?`<div class="product-reading"><h3>Read the selection guide</h3>${productReadings.map(a=>`<a href="../knowledge/${e(a.slug)}.html">${e(a.title)} <span aria-hidden="true">↗</span></a>`).join('')}</div>`:''}<p class="product-disclaimer">Technical descriptions are general screening guidance. Verify food-category permission, use level, labeling and finished-product performance for your destination market.</p></div></section>`+
  cta('Bring us your application brief.','Include the food category, target function, expected volume, destination market and documents you need.',productAction,productInquiry);
  write(`products/${item.slug}.html`,shell({title:item.name+(item.name===item.abbr?'':' ('+item.abbr+')')+(guide?' — Selection Guide':detail?' — Grades & Applications':' — Grade & Buying Questions'),description:`${item.lead} ${guide?'Compare forms, functions and application requirements in this technical selection guide.':detail?'Explore material forms, application selection, specification references and product inquiries.':'Review grade, source and document questions before a proposed purchase.'}`,active:'Products',body}));
}

write('applications/index.html',shell({title:'Food Applications & Ingredient Selection',description:'Start with a food problem in bakery, meat, seafood, dairy, beverages or sauces. Compare candidate ingredient functions, process conditions and trial questions.',active:'Applications',body:
  banner('APPLICATION SELECTION','Start with the food.<br><em>Then choose the ingredient.</em>','Compare food-specific conditions, candidate functions, records and trial observations before preparing an application inquiry.','Applications')+
  `<section class="page-section"><div class="container">${sectionHead('THE WORKING BRIEF','Tell us what the formula<br><span class="serif-accent">needs to do.</span>','The same ingredient name can lead to different decisions in different food matrices. Links marked selection guide provide technical context, not an offer of supply.')}<nav class="family-links" aria-label="Food applications">${applicationItems.map(app=>`<a href="#${app.id}">${e(app.name)}</a>`).join('')}</nav><div class="application-index">${applicationItems.map(item=>applicationContent(item,{e,products,articles,productLink,applicationGoals,applicationInquiry})).join('')}</div></div></section>`+
  cta('What are you trying to improve?','Include the food, process, target function and market. Use the guides to frame the product and document questions for your inquiry.')}));

for (const page of supplyPages({e,banner,sectionHead,cta,inquiryUrl,returnRoutes:returnRoutes(products,articles)})) {
  write(page.path,shell(page));
}

write('privacy/index.html',shell({title:'Privacy & Inquiry Data',description:'Learn how IngredientCore’s static site handles inquiry drafts, URL topics, clipboard actions, email, hosting and external reference links.',active:'',body:
  banner('SITE INFORMATION','Privacy & inquiry data.','What happens when you browse the site or prepare an ingredient inquiry.','Privacy & Inquiry Data')+
  `<section class="page-section"><div class="container"><div class="article-content privacy-content">
    <section class="article-section"><h2>Information you choose to enter</h2><p>The Contact page asks for a name, reply email and ingredient or target function. You may also add a company, food application, destination market, target specification, quantity, document request and other questions. Enter only what is needed for the inquiry; avoid sending a confidential full formula in an initial message.</p><p>Links to Contact may carry a product, application, goal, document topic or reference-page key in the URL. These are intended as non-sensitive context. URLs can be visible to your browser, the hosting service and anyone with whom you share a link. Do not put personal details or confidential formulation information in a URL.</p></section>
    <section class="article-section"><h2>Drafts, copying and email</h2><p>This website has no online form submission endpoint. While you prepare a brief, entries remain in the open browser page. “Open email draft” passes the text to your chosen mail application through a mailto link; you review and send it yourself. If the draft is too long for a reliable link, the full text is shown for manual copying instead.</p><p>“Copy inquiry for webmail” writes the brief to your clipboard only when you choose that action. If clipboard access fails, the page displays selectable text. After you send an email, your mail provider and the receiving email systems handle it under their own arrangements. The website cannot confirm delivery or how long those systems retain a message.</p></section>
    <section class="article-section"><h2>Storage, hosting and other sites</h2><p>Our website does not set cookies, use localStorage or sessionStorage, or load analytics, third-party fonts, embedded content or an external form service. It does not save your unfinished brief for a later visit. Your browser or mail application may offer its own autofill or draft features.</p><p>When you visit, the hosting provider may process access information needed to serve pages. We do not control the provider’s records. Technical articles link to outside references. The WhatsApp contact link opens an external service in a new tab; it does not send a message automatically. Those services are contacted only if you follow a link, and their own practices apply. This site asks the browser not to send the referring page address when navigating away.</p></section>
    <section class="article-section"><h2>Contact and changes</h2><p>For questions about this site or a website inquiry, contact IngredientCore at <a href="mailto:${e(brand.email)}">${e(brand.email)}</a>. IngredientCore is a subsidiary of Bespring Chemical, established in 2025.</p><p>This notice explains how our current inquiry tools work. Please contact us if you have a question about preparing or sending your inquiry.</p></section>
  </div></div></section>`}));

const articleCard=article=>`<a class="knowledge-card" href="${e(article.slug)}.html"><span class="knowledge-card__category">${e(article.category)}</span><h3>${e(article.title)}</h3><p>${e(article.summary)}</p><span class="knowledge-card__read">Read guide <span aria-hidden="true">↗</span></span></a>`;
write('knowledge/index.html',shell({title:'Food Ingredient Buying Guides',description:'Compare ingredients and prepare specification, COA, TDS and supplier qualification questions with practical food ingredient buying guides.',active:'Buying Guides',body:
  banner('THE INGREDIENT LIBRARY','Useful questions.<br><em>Better ingredient decisions.</em>','Explore practical guides to ingredient selection, food applications, documents and source qualification.','Buying Guides')+
  `<section class="page-section knowledge-intro"><div class="container"><div class="knowledge-intro__grid"><div>${sectionHead('PRACTICAL BUYING GUIDES','Turn product names into<br><span class="serif-accent">working decisions.</span>')}</div><div><p>Compare ingredient functions, understand specification fields and prepare questions for your next purchase. Our buying guides cover product comparisons, food applications and supplier documents. Apply technical guidance to the specific grade, food and destination market; related ingredients marked as selection guides are for technical comparison.</p><a href="../contact/index.html">Ask about your application <span aria-hidden="true">↗</span></a></div></div><div class="knowledge-routes"><a href="#ingredient-decisions">Ingredient decisions <span aria-hidden="true">↓</span></a><a href="#buyer-readiness">Buyer readiness <span aria-hidden="true">↓</span></a></div></div></section>`+
  `<section class="page-section page-section--tint" id="ingredient-decisions"><div class="container">${sectionHead('FORMULATION & SELECTION','Compare ingredients<br><span class="serif-accent">with a purpose.</span>')}<div class="knowledge-grid">${articles.slice(0,5).map(articleCard).join('')}</div></div></section>`+
  `<section class="page-section" id="buyer-readiness"><div class="container">${sectionHead('DOCUMENTS & SOURCING','Prepare a stronger<br><span class="serif-accent">qualification brief.</span>')}<div class="knowledge-grid">${articles.slice(5).map(articleCard).join('')}</div></div></section>`+
  cta('Have a specific formulation question?','Include the product, application, target specification, destination market and the records you need to review.')}));

for(const article of articles){
  const sectionId=(heading,index)=>'section-'+(index+1)+'-'+heading.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const sections=article.sections.map((section,index)=>`<section class="article-section" id="${sectionId(section.h,index)}"><span class="article-section__number">${String(index+1).padStart(2,'0')}</span><h2>${e(section.h)}</h2>${(section.p||[]).map(p=>`<p>${e(p)}</p>`).join('')}${section.table?comparisonTable(section.table,e):''}${section.bullets?`<ul>${section.bullets.map(b=>`<li>${e(b)}</li>`).join('')}</ul>`:''}${section.refs?sourceLinks(section.refs,e):''}</section>`).join('');
  const nextArticles=relatedArticles(article,articles);
  const extensionLinks=(articleExtensions[article.slug]||[]).map(([slug,note])=>`<li>${productLink(slug,products.find(p=>p.slug===slug).name)}<p>${e(note)}</p></li>`).join('');
  const articleRequest=articleInquiry(article,products);
  const relatedProducts=article.products.map(slug=>{const product=products.find(p=>p.slug===slug);return productLink(slug,product.name);}).join('');
  const relatedApps=article.applications.map(id=>{const app=applicationItems.find(a=>a.id===id);return `<a href="../applications/index.html#${e(id)}">${e(app.name)} <span aria-hidden="true">↗</span></a>`;}).join('');
  const productRoute=relatedProducts||'<a href="../products/index.html">Explore ingredient guides <span aria-hidden="true">↗</span></a>';
  const applicationRoute=relatedApps||'<a href="../applications/index.html">Explore food applications <span aria-hidden="true">↗</span></a>';
  const body=banner(article.category.toUpperCase(),e(article.title),article.summary,`<a href="index.html">Buying Guides</a> / ${e(article.title)}`)+
    `<section class="page-section article-main"><div class="container article-layout"><article class="article-content"><div class="article-lead"><span>INGREDIENTCORE KNOWLEDGE CENTER</span><p class="content-updated">Content updated <time datetime="${e(article.updated)}">${e(article.updated)}</time></p><p>${e(article.intro)}</p></div>${sections}<aside class="article-boundary"><strong>How to use this guide</strong><p>This article supports initial screening and discussion. For any proposed supply, confirm the product's current specification, source, food-category permission, use conditions and finished-product performance before commercial use.</p></aside><section class="article-sources"><h2>Sources and scope</h2><p>Use identity references, technical explanations and food-system studies for their stated purposes. Match each reference to its stated material, food system and test conditions.</p>${sourcesWithScope(article.sourceIds,e)}</section></article><aside class="article-sidebar"><div class="article-sidebar__box"><span>IN THIS GUIDE</span><nav aria-label="Article sections">${article.sections.map((section,index)=>`<a href="#${sectionId(section.h,index)}">${e(section.h)}</a>`).join('')}</nav></div><div class="article-sidebar__box article-sidebar__box--contact"><strong>Working on a similar brief?</strong><p>Tell us the food, target function and market.</p><a href="${e(articleRequest)}">Prepare inquiry from this guide <span aria-hidden="true">↗</span></a></div></aside></div></section>`+
    `<section class="page-section page-section--tint article-related"><div class="container"><div class="article-related__grid"><div><h2>${relatedProducts?'Ingredients discussed':'Explore ingredient guides'}</h2><div class="article-related__links">${productRoute}</div></div><div><h2>${relatedApps?'Related applications':'Explore applications'}</h2><div class="article-related__links">${applicationRoute}</div></div></div>${extensionLinks?`<section class="article-product-paths"><h2>Apply these questions to related products</h2><ul>${extensionLinks}</ul></section>`:''}<h2>Continue reading</h2><div class="knowledge-grid knowledge-grid--compact">${nextArticles.map(a=>`<a class="knowledge-card" href="${e(a.slug)}.html"><span class="knowledge-card__category">${e(a.category)}</span><h3>${e(a.title)}</h3><p>${e(a.summary)}</p><span class="knowledge-card__read">Read guide <span aria-hidden="true">↗</span></span></a>`).join('')}</div></div></section>`+
    cta('Bring us your own ingredient brief.','Use this framework to specify the product, application, market and documents in your email inquiry.','Prepare inquiry from this guide',articleRequest);
  write(`knowledge/${article.slug}.html`,shell({title:article.title,description:article.summary,active:'Buying Guides',body}));
}

console.log(`Built ${products.length} product pages, ${articles.length} knowledge articles and 7 section pages.`);
