import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const source=fs.readFileSync(path.join(root,'assets/js/site.js'),'utf8');
function setup(search='',initial={},clipboardFails=false,valid=true,recipient='ingredientcore@bespringchem.com'){
 const nodes=[];
 const createNode=()=>({hidden:false,value:'',textContent:'',listeners:{},attributes:{},setAttribute(name,value){this.attributes[name]=value;},getAttribute(name){return this.attributes[name]||'';},removeAttribute(name){delete this.attributes[name];},focus(){this.focused=true;},select(){this.selected=true;},insertAdjacentElement(_position,child){nodes.push(child);},addEventListener(type,callback){this.listeners[type]=callback;}});
 const values={name:'Alex Buyer',email:'alex@example.com',company:'Example Foods',market:'Canada',ingredient:'',application:'Frozen bakery mix',volume:'2 tonnes per month',specification:'Slow reaction profile',documents:'',purpose:'',details:'25 kg bags',inquiry_type:'Ingredient inquiry',...initial};
 const submit=createNode();
 const limits={name:150,email:254,ingredient:200,company:200,market:120,application:200,goal:200,volume:150,specification:2000,documents:1200,purpose:500,details:2000};
 const form={elements:Object.fromEntries(Object.entries(values).map(([key,value])=>{const control=Object.assign(createNode(),{value});if(limits[key])control.attributes['data-limit']=String(limits[key]);return[key,control];})),listeners:{},getAttribute:name=>name==='data-inquiry-email'?recipient:null,reportValidity:()=>valid,querySelector:()=>submit,addEventListener(type,callback){this.listeners[type]=callback;}};
 const location={search,href:''},copied={text:''};
 vm.runInNewContext(source,{document:{querySelector:selector=>selector==='[data-contact-form]'?form:null,createElement:createNode},window:{location},navigator:{clipboard:{async writeText(value){if(clipboardFails)throw Error('denied');copied.text=value;}}},URLSearchParams,FormData:class{get(name){return form.elements[name]?.value??'';}}});
 return{form,location,copied,nodes,copy:nodes.find(node=>node.textContent==='Copy inquiry for webmail'),status:nodes.find(node=>node.className==='contact-form__status'),preview:nodes.find(node=>node.className==='contact-form__preview')};
}
const ordinary=setup('?ingredient=SAPP');
assert.equal(ordinary.form.elements.ingredient.value,'SAPP');
assert.equal(ordinary.form.elements.inquiry_type.value,'Ingredient inquiry');
const requested=setup('?'+new URLSearchParams({intent:'documents',ingredient:'SAPP',documents:'TDS and representative COA',purpose:'Supplier approval'}));
assert.equal(requested.form.elements.inquiry_type.value,'Product document request');
assert.equal(requested.form.elements.documents.value,'TDS and representative COA');
assert.equal(requested.form.elements.purpose.value,'Supplier approval');
requested.form.listeners.submit({preventDefault(){}});
const draft=new URL(requested.location.href);
assert.equal(draft.protocol,'mailto:');
assert.equal(draft.pathname,'ingredientcore@bespringchem.com');
for(const field of ['Frozen bakery mix','Slow reaction profile','Canada','Product document request','Supplier approval','TDS and representative COA'])assert.ok(draft.searchParams.get('body').includes(field));
await requested.copy.listeners.click();
assert.ok(requested.copied.text.includes('Purpose of document request: Supplier approval'));
assert.ok(requested.copied.text.includes('Inquiry type: Product document request'));
const preserved=setup('?ingredient=SAPP&documents=COA&purpose=Review',{ingredient:'CMC',documents:'Specification',purpose:'Trial'});
assert.equal(preserved.form.elements.ingredient.value,'CMC');
assert.equal(preserved.form.elements.documents.value,'Specification');
assert.equal(preserved.form.elements.purpose.value,'Trial');
const excessive=setup('?'+new URLSearchParams({ingredient:'x'.repeat(201),documents:'x'.repeat(1201),purpose:'x'.repeat(501),intent:'other'}));
for(const field of ['ingredient','documents','purpose'])assert.equal(excessive.form.elements[field].value,'');
assert.equal(excessive.form.elements.inquiry_type.value,'Ingredient inquiry');
const oversizedQuery=setup('?ingredient=SAPP&padding='+'x'.repeat(5000));
assert.equal(oversizedQuery.form.elements.ingredient.value,'');
const lineBreakQuery=setup('?ingredient=SAPP%0ABcc%3Aother%40example.invalid');
assert.equal(lineBreakQuery.form.elements.ingredient.value,'');
const literal=setup('?ingredient='+encodeURIComponent('<img src=x onerror=alert(1)>'));
assert.equal(literal.form.elements.ingredient.value,'<img src=x onerror=alert(1)>');
const fallback=setup('?ingredient=SAPP',{},true);
await fallback.copy.listeners.click();
const preview=fallback.nodes.find(node=>node.className==='contact-form__preview');
assert.equal(preview.hidden,false);
assert.ok(preview.focused&&preview.selected&&preview.value.includes('Ingredient or target function: SAPP'));
const invalid=setup('',{},false,false);
invalid.form.listeners.submit({preventDefault(){}});
await invalid.copy.listeners.click();
assert.equal(invalid.location.href,'');
assert.equal(invalid.copied.text,'');
const routed=setup('?ingredient=CMC',{},false,true,'designated@example.com');
routed.form.listeners.submit({preventDefault(){}});
await routed.copy.listeners.click();
assert.equal(new URL(routed.location.href).pathname,'designated@example.com');
assert.ok(routed.copied.text.startsWith('To: designated@example.com'));
const long=setup('?ingredient=SAPP',{details:'Long detail '.repeat(150)});
long.form.listeners.submit({preventDefault(){}});
assert.equal(long.location.href,'');
assert.equal(long.preview.hidden,false);
assert.ok(long.preview.value.includes('Long detail '.repeat(150).trim()));
assert.match(long.status.textContent,/too long/);
const special=setup('?ingredient='+encodeURIComponent('SAPP & SALP / bakery'),{details:'pH 5–6 & heat\nHold until ready'});
special.form.listeners.submit({preventDefault(){}});
const specialUrl=new URL(special.location.href);
assert.ok(specialUrl.searchParams.get('body').includes('pH 5–6 & heat\nHold until ready'));
await special.copy.listeners.click();
assert.ok(special.copied.text.includes('pH 5–6 & heat\nHold until ready'));
special.form.elements.ingredient.value='Sodium CMC';
special.form.listeners.input();
assert.equal(special.status.textContent,'');
await special.copy.listeners.click();
assert.ok(special.copied.text.includes('Ingredient or target function: Sodium CMC'));
assert.ok(!special.copied.text.includes('Ingredient or target function: SAPP'));
const controlTopic=setup('',{ingredient:'SAPP\r\nBcc: other@example.invalid',inquiry_type:'Product\r\nBcc: other@example.invalid'});
controlTopic.form.listeners.submit({preventDefault(){}});
const controlDraft=new URL(controlTopic.location.href);
assert.ok(!/[\r\n]/.test(controlDraft.searchParams.get('subject')));
assert.ok(controlDraft.searchParams.get('body').includes('SAPP\r\nBcc: other@example.invalid'));
const badEmail=setup('?ingredient=SAPP',{email:'broken-address'});
badEmail.form.listeners.submit({preventDefault(){}});
assert.equal(badEmail.location.href,'');
assert.equal(badEmail.form.elements.email.attributes['aria-invalid'],'true');
assert.ok(badEmail.form.elements.email.focused);
const tooLong=setup('?ingredient=SAPP',{details:'x'.repeat(2001)});
tooLong.form.listeners.submit({preventDefault(){}});
assert.equal(tooLong.location.href,'');
assert.equal(tooLong.form.elements.details.attributes['aria-invalid'],'true');
assert.equal(tooLong.form.elements.details.value.length,2001);
const sample=setup('?intent=sample&purpose=Sample%20availability&ingredient=SAPP');
assert.equal(sample.form.elements.inquiry_type.value,'Sample availability question');
sample.form.elements.inquiry_type.value='Product document request';
sample.form.listeners.submit({preventDefault(){}});
assert.ok(new URL(sample.location.href).searchParams.get('body').includes('Product document request'));
console.log('Contact checks passed: four request routes, prefill, edited values, field errors, special characters, long mailto fallback, copy parity and failure fallback. No email sent.');
