// Original procurement explanations. References specify what evidence supports.
import {brand} from './brand.mjs';
import {sourceTuples} from './technical-sources.mjs';
const details={
 'stpp-vs-shmp':{
  summary:'Compare phosphate identity, reporting basis and process conditions before evaluating protein-water or mineral-management tasks.',
  intro:'STPP and SHMP are distinct materials. Choose a comparison around an observable food problem, then qualify the grade and source. A shared phosphate family or similar assay figure cannot settle functional equivalence.',
  sections:[
   {h:'Confirm identity before comparing numbers',p:['JECFA names STPP as pentasodium triphosphate and lists commercial SHMP as sodium polyphosphate, glassy. The identities are different; neither entry identifies the exact grade offered.','Ask whether “phosphate content” means a compound assay, phosphorus or another equivalent expression. Record analytical basis, method and units rather than comparing percentages with different meanings.'],refs:['stpp','shmp']},
   {h:'Separate meat and seafood questions',p:['For meat or poultry, describe protein source, salt, starting pH, brine preparation, injection/tumbling, holding and cooking. For seafood, add species, peeled/whole form, previous freezing, treatment contact, draining and thaw protocol. Uptake during treatment differs from water retained after processing.','A published buffalo-meat/patty study compared phosphate treatments within a defined salt system. It illustrates why food and treatment conditions belong in the comparison; its ranking and numerical results are not predictions for another species, process or source.'],refs:['beef']},
   {h:'Keep a mineral-management brief specific',p:['Sequestration means binding metal ions in a way that can change their availability in the system. If mineral-related sediment is the concern, identify the water, fortification salts, protein, pH and heat step. First describe the sediment and when it appears.','Review composition and dissolution information for the source. A solution observation does not establish the result in a protein-containing drink; clarify the failure mechanism before calling a candidate a solution.']},
   {h:'Prepare a comparison record',table:{caption:'Questions for a phosphate comparison',headers:['Record','Compare on the same basis','Reason'],rows:[['Material','Producer, grade and specification revision','Connect observations to the material tested.'],['Preparation','Water, concentration, temperature and mixing','pH and dissolution need context.'],['Food/process','Recipe, salt, hold and heat/freeze history','Separate material and process differences.'],['Outcome','Defined mass stages, texture and sensory methods','Yield needs a denominator and method.']]}},
   {h:'Plan trial and purchase together',bullets:['Keep the current formulation/process as benchmark; have the technical team select a suitable baseline and replicate plan.','Record candidate grade, addition basis, preparation and recipe changes. Do not assume an equal-weight swap is a fair comparison.','Define observations after treatment/draining and after relevant cooking/thawing.','Request current grade records, representative COA and reporting/test methods; confirm sharing permission.','Review food-category permission, labeling and commercial conditions separately from trial performance.']},
   {h:'Avoid the family-name shortcut',p:['Neither material is universally better. Select against agreed outcomes and acceptance criteria, then connect the sample, source records and proposed order. A batch COA reports chemistry; it cannot establish cooked yield or storage behavior in the customer’s food.']}
  ],sourceIds:['stpp','shmp','beef'],inquiryGoal:'Phosphate grade and process comparison',requestedDocuments:'Current grade specification, representative COA, assay/reporting basis and pH/dissolution methods; confirm availability',requestPurpose:'Phosphate comparison and source qualification'},
 'sapp-vs-salp-bakery':{
  summary:'Separate acid–bicarbonate balance from gas-release timing, then compare named grades under the actual hold and baking schedule.',
  intro:'Compare SAPP with an exactly identified acidic SALP grade as parts of a complete chemical leavening system. The question is how the acid component and bicarbonate behave through mixing, holding and heating—not whether two names sound similar.',
  sections:[
   {h:'Resolve the material and grade',p:['SAPP identity does not define a reaction-rate grade. The JECFA SALP reference here is specifically the acidic material; an unspecified sodium aluminum phosphate label needs clarification before a bakery comparison.','Request grade designation, source, particle information, reaction-test definition and neutralizing-value basis where supplied. A monograph is not a reaction certificate for the offered grade.'],refs:['sapp','salp']},
   {h:'Distinguish balance from timing',p:['Neutralizing value describes acid capacity in relation to bicarbonate on a stated basis. Reaction rate describes when gas is generated under specified conditions. A rate code does not by itself balance acid and bicarbonate.','ICL’s technical paper explains balance and model dough reaction measurements for its materials. Its curves are method- and grade-specific: use them to understand what to ask for, not as curves for IngredientCore supply.'],refs:['leavening']},
   {h:'Map the process window',table:{caption:'The timeline to include in a leavening brief',headers:['Stage','Record','Observe'],rows:[['Mixing','Water addition, order, temperature and mixing','Initial consistency and gas development.'],['Holding','Duration, temperature and chilling/freezing','Loss of lift or batter changes.'],['Heating','Pan/portion and oven profile','Lift, shape and setting.'],['Finished food','Cooling and evaluation methods','Volume, crumb, pH and sensory outcome.']]}},
   {h:'Avoid an unbalanced substitution test',p:['Keep the current system unchanged as benchmark. Have the formulator review acid–bicarbonate balance before testing candidates. Record changes to bicarbonate or other ingredients explicitly; a balance difference must not be mistaken for a reaction-rate difference.','Keep flour lot, portioning and heating comparable. Compare fresh and held batter under the actual schedule. A waffle study examined leavening alongside fat and water variables; its findings concern that fresh-egg waffle system.'],refs:['waffle']},
   {h:'Request a testable grade description',bullets:['Food and current leavening system, including other acid components.','Mix-to-bake timeline, temperature, chilling/freezing and bake profile.','Reaction method, model recipe, sampling times and grade-code definition.','Neutralizing-value definition/basis and current specification, if available.','Sample identity and its correspondence to the commercial source; intended food category and market.']},
   {h:'Review the market separately',p:['Baking trials inform lift, crumb and sensory decisions. They do not establish local permission, aluminum-related requirements or label wording. Check the exact material, food category and destination conditions without extending one market’s rule to another.']}
  ],sourceIds:['sapp','salp','leavening','waffle'],inquiryGoal:'Leavening balance, reaction grade and hold tolerance',requestedDocuments:'Exact-grade specification, reaction test, neutralizing-value basis and representative COA; confirm availability',requestPurpose:'Bakery leavening grade comparison'},
 'propionates-and-sorbates':{
  summary:'Define spoilage, food pH, water activity, incorporation and packaging before comparing preservative materials.',
  intro:'Begin with the spoilage issue and complete food/process/package system. Propionates and sorbates are candidate materials for discussion, not a universal way to establish food safety or a fixed shelf-life extension.',
  sections:[
   {h:'Describe the failure before naming an ingredient',p:['Record when the defect appears, what professional investigation has identified, and the food, package and storage conditions. Bakery mold, yeast in a drink and a safety hazard are different questions. Visual absence of spoilage does not establish safety.','Water activity (aw) describes water availability, not total moisture. If measured, record method and temperature. Pair it with pH, process, package and storage rather than treating either number as standalone approval.'],refs:['waterActivity']},
   {h:'Why food and pH matter',p:['Propionic and sorbic acids are weak acids: the balance between dissociated and undissociated forms depends on pH. A salt identity is not a finished-food inhibition result. A study of acids/salts in media and selected animal products found that results depended on test environment; its inhibition values are not food-use recommendations.','Define actual food pH, composition, ingredient distribution and existing controls. Do not transplant a laboratory threshold, another manufacturer’s dose or an acid result to an unspecified salt grade.'],refs:['preservation']},
   {h:'Compare material and incorporation',table:{caption:'A preservative comparison brief',headers:['Question','Record','Do not infer'],rows:[['Identity','Exact salt, grade and form','A name does not define efficacy in food.'],['Handling','Preparation, dissolution/dispersion, addition point','Equal weight does not mean equal distribution/effect.'],['Food','pH, aw if known, composition, process and package','One matrix result is not universal.'],['Acceptance','Qualified study design and agreed criteria','A COA is not a finished-food shelf-life study.']]}},
   {h:'Separate spoilage and safety control',p:['Hygiene practices and hazard controls remain necessary. A preservative cannot replace sanitation, a required heat process, cold-chain control or other measures identified for the food. Review safety with the responsible food-safety personnel.','Microbiological validation needs suitable professional capability and methods. Ask the qualified team to determine relevant organisms, storage conditions, sampling and acceptance criteria; this article supplies no culturing protocol or microbiological safety conclusion.'],refs:['hygiene']},
   {h:'Prepare study and document requests',bullets:['Use the current system as benchmark and have qualified personnel select suitable controls.','Record source/grade, preparation and addition basis, plus other formula/process changes.','Assess package and storage as well as microbial outcomes; assess sensory/texture only on samples cleared as appropriate by the responsible team.','Request exact-form specification and representative COA; ask about current SDS/storage records and sharing permission.','Review destination food-category permission and labeling separately. No universal dose or storage duration is given.']}
  ],sourceIds:['waterActivity','preservation','hygiene'],inquiryGoal:'Food-specific spoilage and incorporation review',requestedDocuments:'Exact identity/form specification, representative COA and applicable safety/storage information; confirm availability',requestPurpose:'Preservative material and source screening'},
 'hydrocolloid-selection':{
  summary:'Compare hydration, flow and gel behavior in the named food system, using viscosity and gel measurements with matching methods.',
  intro:'Choose the behavior first: suspension at rest, pouring, gel texture or resistance to liquid separation. Sodium CMC, xanthan and carrageenan grades are not equal-dose substitutes. A laboratory viscosity number cannot define all these outcomes.',
  sections:[
   {h:'Translate the defect into an observation',p:['Rheology describes how material flows or deforms under defined movement or force. Shear is deformation during mixing, pumping or pouring. A drink that suspends solids at rest and pours easily needs both observations, not one thickness reading.','Syneresis means liquid released from a gel. Distinguish it from sediment, oil separation, protein aggregates and poorly hydrated gum. Identify what separates, when and whether it redistributes before changing ingredients.']},
   {h:'Compare grade and measurement',table:{caption:'Grade information for three hydrocolloids',headers:['Material','Request','Comparison boundary'],rows:[['Sodium CMC','Viscosity range, concentration, preparation, temperature and instrument/settings; substitution information if relevant','A viscosity label without its method is incomplete.'],['Xanthan','Solution composition, viscosity method, particle profile and hydration procedure','Compare rest/pouring behavior in food; mesh alone is not a grade.'],['Carrageenan','Type, process identity, composition/blend and gel/viscosity method','Match ionic recipe, preparation, temperature and units.']]}},
   {h:'Separate gel families and stabilizer systems',p:['FAO’s technical guide distinguishes carrageenan types, including non-gelling lambda and ionic conditions relevant to kappa/iota gel behavior. “Carrageenan” is therefore too broad for a gel specification; this distinction does not define a particular blend’s result.','Sodium CMC identity is separate from its viscosity grade. Review source identity and food/market requirements alongside trials, rather than waiting until texture looks acceptable to start source qualification.'],refs:['carrageenan','cmc']},
   {h:'Do not transfer dairy results to plant bases',p:['Name proteins, minerals, particles, oil phase and heat history. Dairy proteins, soy isolate and an oat base are different systems. A milk-tea screening study and a soy-protein/rice-bran-oil model-emulsion study examined specific formulations and preparation conditions; neither establishes a universal stabilizer.','The soy model used laboratory preparation and reagents. It is a reason to examine system conditions, not an edible recipe or commercial process. No experimental dose is copied here.'],refs:['milkTea','soy']},
   {h:'Prepare a controlled texture trial',bullets:['Record water/minerals, pH, proteins, salts, other gums and oil/solid phases.','Separate dispersion from hydration: dispersion distributes particles; hydration develops the dissolved/swollen state needed for grade behavior.','Keep a current-system benchmark; record addition order, mixing, hydration time, heat, cooling and homogenization.','Measure viscosity with temperature, instrument/settings and time after processing; observe flow or gel setting as relevant.','Check sediment, liquid/oil separation, redispersibility and sensory texture through intended storage.','Ask for current grade specification and test methods. No generic replacement ratio is assumed.']}
  ],sourceIds:['cmc','carrageenan','milkTea','soy'],inquiryGoal:'Hydration, flow or gel comparison in a named food',requestedDocuments:'Grade specification, viscosity/gel method, hydration guidance and blend composition where relevant; confirm availability',requestPurpose:'Hydrocolloid comparison and application screening'},
 'citric-acid-vs-sodium-citrate':{
  summary:'Separate pH, titratable acidity, sourness, buffering and mineral questions before comparing the exact acid or citrate form.',
  intro:'Citric acid and sodium citrate serve different roles in acidity and buffering. Begin with the measurement or sensory change needed; they are not equal-weight substitutes.',
  sections:[
   {h:'Name the acidity question',table:{caption:'Different acidity measurements answer different questions',headers:['Term','Meaning','Record'],rows:[['pH','A measure based on hydrogen-ion activity','Preparation, temperature and measurement method.'],['Titratable acidity (TA)','Acid-neutralizing demand to a defined endpoint','Endpoint, units and reference-acid basis.'],['Buffering','Resistance to pH change when acid/base is added','Relevant composition and comparison method.'],['Sourness','Sensory perception in the complete food','Controlled sensory conditions, sugar/flavor and serving context.']]},refs:['acidity']},
   {h:'Similar pH does not mean the same taste',p:['Discuss citric acid for acid addition and an identified citrate salt for acid–salt balance or mineral questions. Measure pH, TA and sensory outcome separately rather than using one as a proxy for all three.','A human sensory study compared aqueous citric-acid/citrate mixtures and found that composition influenced perception. Aqueous results do not predict sourness in a sweetened, protein-containing or otherwise complex food.'],refs:['sourness']},
   {h:'Specify the form before calculating a change',p:['Name anhydrous or monohydrate citric acid and the exact sodium citrate salt/hydrate. Hydration and salt identity affect formula calculation and assay basis. Do not convert unspecified forms by equal weight.','Include sodium/mineral contribution and protein conditions in the complete formulation. Record precipitation or protein changes separately rather than assuming that reaching a pH target solves them.']},
   {h:'Build a testable comparison',bullets:['State whether the objective is lower pH, changed sourness, buffering or a mineral-related defect.','Keep a current-formula benchmark; record acid/salt changes, identity and reporting bases.','Define pH and TA methods, including temperature, sample preparation and titration endpoint.','Record water/minerals, heat, filling, pack and storage; examine texture/precipitation separately.','Evaluate sensory outcome in the complete food. Do not infer safety from acidity or taste.']},
   {h:'Request identity and evidence',p:['If a source is proposed, request its exact-form specification, assay method and representative COA, and confirm sharing permission. Review market-specific use conditions separately. This article gives no dose or validated preservation process.']}
  ],sourceIds:['acidity','sourness'],inquiryGoal:'Acidity measurements and exact-form comparison',requestedDocuments:'Exact salt/hydrate or acid-form specification, assay basis and representative COA if a source is proposed; confirm availability',requestPurpose:'Additional technical selection comparison'},
 'specification-tds-coa':{
  summary:'Match agreed limits, typical properties and sample/batch results to the same material, source, revision and methods.',
  intro:'A specification identifies proposed or agreed material limits. A Technical Data Sheet (TDS) explains context. A Certificate of Analysis (COA) reports an identified sample or batch. Reading them together is more useful than asking for an unspecified certificate.',
  sections:[
   {h:'Use each document for its actual question',table:{caption:'Document purposes and evidence boundaries',headers:['Record','Use it to check','Does not establish'],rows:[['Specification','Identity/grade, limits, units, methods, revision and agreement status','That every value was tested on every batch.'],['TDS (Technical Data Sheet)','Description, typical properties and technical context','That typical values are guaranteed limits.'],['COA (Certificate of Analysis)','Sample/lot, tests, methods and reported results','Future batches or finished-food performance.'],['SDS (Safety Data Sheet)','Material-specific hazards and handling information','Food-grade status or order conformity.']]},refs:['sds']},
   {h:'Resolve identity and scope before values',p:['Match the offer, specification and COA: exact material, form/blend, producer/packing source and grade. A shared abbreviation can conceal another form or method. Confirm whether a specification is a reference example, proposed source record or agreed order version.','Keep a cross-reference between source, document title/revision, sample/lot and material. An older stored document does not necessarily describe the current offer.']},
   {h:'Investigate a numerical disagreement',bullets:['Check analyte and basis: compound assay is not automatically a phosphorus expression.','Match units, dry/as-is basis if relevant, solution concentration, preparation and temperature.','For viscosity/gel results compare instrument/settings and the method’s recipe or ionic conditions.','Distinguish typical value, limit and individual result; ask what “conforms” means if no result is listed.','Clarify scope and method before deciding equivalent or nonconforming.']},
   {h:'Certificates are separate evidence',p:['A management-system certificate needs a named holder, site, scope, issuing body and validity review. ISO explains that external bodies perform certification; an ISO name nearby does not make every product certified.','Source/product declarations need their own identity and conditions. Ask about Halal, Kosher, allergens, GMO, origin or other records for the specific source; do not assume a complete package exists.'],refs:['iso']},
   {h:'Connect sample review to receiving checks',p:['A representative COA supports early review. For an order, agree source/grade/specification version, expected batch records and deviation handling. Separate document review from sampling/testing required by the buyer’s acceptance plan.','These are matters to agree for a purchase, not evidence of an audited IngredientCore receiving, traceability or change-control system.']},
   {h:'Request version and sharing permission',bullets:['Give product/grade, food application, market and review purpose.','Name relevant records and methods; ask if current applicable versions can be shared.','Resolve issuer/site/grade differences and missing units or methods.','Agree a suitable sharing route for restricted files; a hidden public link is not protection.']}
  ],sourceIds:['sds','iso'],inquiryGoal:'Document identity, scope and methods',inquiryIntent:'documents',requestedDocuments:'Current specification, relevant TDS, representative/batch COA information and methods; confirm availability and sharing permission',requestPurpose:'Specification and document correspondence review'},
 'qualify-ingredient-source':{
  summary:'Separate transaction roles, source evidence, application trials and commercial acceptance when assessing a proposed ingredient source.',
  intro:'Assess a defined material from a defined source for a defined intended use. A contact brand, familiar chemical name or certificate image cannot resolve the source, grade, safety evidence and order conditions.',
  sections:[
   {h:'Confirm who performs each role',table:{caption:'Roles to resolve for a proposed purchase',headers:['Role','Ask','Cross-check'],rows:[['Brand/contact','Who answers the inquiry?','Contact details and correspondence identity.'],['Seller/invoice/exporter','Which legal entity performs each relevant role?','Quotation and proposed transaction records.'],['Producer/packer','Who makes/packs the grade and at which site?','Specification, label and applicable source records.'],['Certificate holder','Which entity/site/activity are covered?','Issuer, scope, status and applicability.']]}},
   {h:'Match company records to the proposed supply',p:[brand.established+' When reviewing certificates, match the named holder, site and scope to the proposed supply. Our subsidiary relationship does not extend parent-company certificates to IngredientCore products.','Resolve exact transaction identities. Do not infer producer, seller, exporter or authorization from a shared email domain or a record issued to another entity.']},
   {h:'Choose verification from hazard and intended use',p:['Review identity/specifications with food/process hazards and buyer acceptance needs. Verification may involve records, sampling/testing, audit or other appropriate activities; a generic checklist cannot choose them for every source.','FDA describes a risk-based supply-chain program for hazards needing a supply-chain-applied control when that US framework applies. Connect evidence with the buyer’s hazard analysis; do not assume every reader has the same legal duties.'],refs:['supply']},
   {h:'Connect the sample to the order',bullets:['Identify sample producer, grade, specification revision and associated records.','Compare function with a current benchmark in the actual food/process.','Agree source/grade/version, receiving checks, expected documents and deviation handling.','Discuss source/specification changes, complaint contacts and nonconforming material handling; record agreed arrangements.','Confirm pack/label, storage/date basis, volume, destination, timing and transport responsibilities.']},
   {h:'Record the qualification decision',p:['A buyer record can list material/source, evidence reviewed, trial conditions/results, open questions and approval owner. Revisit it after a relevant source, grade, specification or process change.','Agree the arrangements for source or specification changes, complaint contacts and nonconforming deliveries before ordering, and record the agreed responsibilities.']}
  ],sourceIds:['supply','iso'],inquiryGoal:'Source identity and qualification requirements',inquiryIntent:'documents',requestedDocuments:'Current product/source specification and applicable qualification records; confirm availability and sharing permission',requestPurpose:'Proposed source qualification'},
 'write-ingredient-brief':{
  summary:'Give the food, observed problem, process, evaluation method, grade requirements and purchasing context in one readable inquiry.',
  intro:'A useful brief connects ingredient identity with the food and the decision you need. Separate technical observations from purchasing conditions so the reply can address the relevant grade, records and questions.',
  sections:[
   {h:'State the decision, not just the ingredient',p:['Say whether you need an exact grade, comparison, document review or candidate for a defined problem. Give the food and benchmark. “Thicker,” “food grade” and “better shelf life” need a measurement or observable defect.','Describe what is measured, the method, and what still needs evaluation. A customer target is not a supplier guarantee.']},
   {h:'Select details for the application',table:{caption:'Context to include in a technical inquiry',headers:['Application','Useful details','Evaluation question'],rows:[['Bakery','Acid/bicarbonate system, mixing, hold and heat','What happens to lift, crumb or pH after holding?'],['Meat/seafood','Protein/species, salt, treatment and draining/cooking/thawing','At which mass stage or texture observation does the defect occur?'],['Drink/sauce','pH/minerals, proteins/particles, hydration, heat and shear','Is the issue settling, aggregation, separation or flow?'],['Preservation','Observed spoilage, aw/pH, process, pack and storage','What qualified study and criteria are planned?']]}},
   {h:'Keep evidence requests precise',bullets:['Name exact form/grade if known, current benchmark and relevant specification fields.','Provide test methods with figures: viscosity conditions or reaction/gel definition.','State food category and destination for the buyer’s use/label review.','Request relevant specification, TDS, COA, SDS or source records; ask about availability and sharing permission.','Give trial/order quantity, destination and timing as needs to discuss, not assumed stock/sample terms.']},
   {h:'Teaching example: a bakery comparison inquiry',p:['Illustrative wording only—not a customer case, validated formula or supply offer:','“We are comparing a leavening acid for a prepared bakery batter held before baking. Our current system is identified in the attached specification. The issue is loss of lift after holding. Please discuss the exact SAPP or acidic SALP grade and available reaction-test/neutralizing-value information. We can provide mixing, hold and bake conditions for comparison. Please confirm specification and representative COA availability, proposed source, sample terms and commercial conditions for our stated destination market.”','Replace general wording with measured conditions in your own email. Establish final grade, formulation and acceptance through the appropriate review and trials.']},
   {h:'Protect detail and keep the next step clear',p:['Share detailed recipes/restricted records only through an agreed communication method. Site links carry public product/application context, not names, email addresses or customer formulas.','Contact prepares a draft or copied brief; you send it yourself. Clicking does not submit online, upload an attachment, approve records or deliver documents.']}
  ],sourceIds:['leavening'],inquiryGoal:'Prepare a testable ingredient and application brief',inquiryIntent:'comparison',requestedDocuments:'Relevant current grade specification and test methods; confirm availability',requestPurpose:'Application and purchasing brief'}
};
export function enhanceArticles(base){
 return base.map(article=>{
  const detail=details[article.slug];if(!detail)throw new Error('Missing technical review '+article.slug);
  return {...article,...detail,updated:'2026-09-30',sources:sourceTuples(detail.sourceIds)};
 });
}
