// Product-specific editorial content. Numerical references stay in specifications.mjs.
// These passages explain selection, not tested performance of an offered grade.
const entry=(heading,introduction,forms,trial,handling,related,applications,readings)=>({heading,introduction,forms,trial,handling,related,applications,readings});
const docs='specification-tds-coa', brief='write-ingredient-brief';
export const phosphateDetails={
 'sodium-tripolyphosphate-stpp':entry('Phosphate selection for protein and mineral systems',
  'Our STPP product discussion starts with the food and processing route. In meat and seafood systems, phosphate selection involves protein interactions, salt, water and process history. A successful comparison separates ingredient uptake from moisture retained after cooking or thawing.',
  'Powder and granular grades can behave differently during incorporation. A phosphorus result alone does not describe phase composition, particle distribution or dissolution. Compare those characteristics alongside the assay when transferring a recipe between grades.',
  'Use the same raw material, salt level, treatment time and temperature for the candidate and benchmark. Record uptake, drain loss, cook or thaw loss, texture and sensory observations separately.',
  'Tell us whether bags feed a dry blender or a brine preparation step. Include the receiving and handling conditions so that pack format, moisture protection and the source’s storage instructions can be addressed in the offer.',
  ['sodium-hexametaphosphate-shmp','tetrasodium-pyrophosphate-tspp','potassium-tripolyphosphate-ktpp'],['meat-seafood'],['stpp-vs-shmp',docs]),
 'sodium-hexametaphosphate-shmp':entry('Mineral management with a commercial polyphosphate',
  'SHMP is relevant when mineral interactions, dispersion or a phosphate system are part of the formulation problem. In a beverage, clarity and sediment may matter most; in a protein food, processing and texture introduce a different set of observations.',
  'Commercial SHMP is a glassy polyphosphate material. Its name does not define one pure ring compound or one chain-length distribution. Total phosphate, inactive phosphate and solution behavior describe different aspects of a grade.',
  'Compare the actual process water, mineral load, pH and heating sequence. Record solution preparation, initial clarity and changes after the intended hold or storage period rather than judging only the freshly mixed sample.',
  'Include your dissolution step and water conditions in the inquiry. Ask for the pack format and source-specific storage and shelf-life information alongside the selected grade.',
  ['sodium-tripolyphosphate-stpp','potassium-metaphosphate-kmp'],['beverages','meat-seafood'],['stpp-vs-shmp',docs]),
 'sodium-acid-pyrophosphate-sapp':entry('Match leavening behavior to the production schedule',
  'SAPP supplies an acid component in chemical leavening systems. The practical question is when gas develops after mixing and during heating, and whether the batter or dough can retain it through the production schedule.',
  'Chemical assay and commercial reaction grade answer different questions. A grade selected for a short mix-to-bake interval may not suit a line with extended holding. Reaction tests are comparable only when their procedures and conditions match.',
  'Compare acid–bicarbonate balance, batter temperature, mixing and holding time. Observe pH, rise, crumb, shape and taste with the same flour and heating profile.',
  'For dry mixes, describe blending and moisture exposure before packing. Ask us about the proposed pack, sample terms and the storage conditions stated for that commercial reaction grade.',
  ['sodium-aluminum-phosphate-salp','monocalcium-phosphate-mcp','monocalcium-phosphate-anhydrous'],['bakery'],['sapp-vs-salp-bakery',brief]),
 'sodium-dihydrogen-phosphate-msp':entry('The acidic member of the sodium orthophosphate family',
  'MSP contributes to phosphate buffer systems where the balance of acidic and more alkaline components matters. We invite inquiries that describe the finished food, target pH behavior and the other salts already in the recipe.',
  'Anhydrous, monohydrate and dihydrate materials differ in water content and mass basis. Product names on the sample, specification and quotation should identify the same form; equal weights of different hydrates are not automatically equivalent.',
  'Compare pH after mixing and after the actual heating or holding step. In mineral- or protein-containing foods, also observe sediment, separation and texture under the same conditions.',
  'Specify the hydration form and whether the material is dissolved or dry blended. Pack format and storage instructions should relate to that form and its proposed source.',
  ['disodium-phosphate-dsp','trisodium-phosphate-tsp','monopotassium-phosphate-mkp'],['beverages'],[docs,brief]),
 'disodium-phosphate-dsp':entry('Buffer balance in formulated foods',
  'DSP occupies a different position from MSP and TSP in a sodium orthophosphate system. It can be considered in discussions of buffering and mineral balance, where final pH alone may not describe the response of a complete food.',
  'The hydration form and assay basis are central to a purchase description. An assay expressed as anhydrous sodium phosphate does not mean that the physical material itself is anhydrous.',
  'Keep proteins, minerals, water and heating consistent across trials. Follow pH, visible separation, sediment and texture through processing and the intended observation period.',
  'Include the exact form, receiving conditions and preparation step. Ask for its current label, pack options and storage and shelf-life statement with the specification.',
  ['sodium-dihydrogen-phosphate-msp','trisodium-phosphate-tsp','dipotassium-phosphate-dkp'],['dairy','beverages'],[docs,brief]),
 'trisodium-phosphate-tsp':entry('Alkaline orthophosphate selection',
  'TSP brings a more alkaline contribution than the less neutralized sodium orthophosphates. Selection therefore begins with the required food-system response and the complete acid, salt and mineral balance.',
  'Anhydrous and hydrated TSP require separate material descriptions and calculations. Drying loss, assay expression and hydration identity must be read together; a water-related value is not interchangeable with phosphate content.',
  'Observe pH through the process, not just in a stock solution. Compare taste, mineral precipitation and protein response where relevant, using the same water and addition sequence.',
  'Describe the handling route and exact form in your inquiry. Use the offered material’s safety and storage information when planning receiving and preparation.',
  ['disodium-phosphate-dsp','sodium-dihydrogen-phosphate-msp','tripotassium-phosphate-tkp'],['beverages'],[docs,brief]),
 'tetrasodium-pyrophosphate-tspp':entry('An alkaline pyrophosphate for phosphate-system comparisons',
  'TSPP and SAPP are different materials even though both are pyrophosphates. In protein-food discussions, the alkaline contribution and interactions of TSPP should be evaluated within the complete salt and phosphate system.',
  'Anhydrous and hydrated material cannot share a water-loss assumption. Also distinguish assay after a specified treatment from an as-received result when comparing specifications.',
  'Prepare the candidate under the same dissolution, mixing and temperature conditions as the benchmark. Record pH, undissolved material and the finished food’s texture and separation or moisture behavior.',
  'State the form and whether you prepare a brine, slurry or dry mix. Request packaging and label details specific to the offered source, rather than using an unrelated phosphate’s storage period.',
  ['sodium-tripolyphosphate-stpp','tetrapotassium-pyrophosphate-tkpp','sodium-acid-pyrophosphate-sapp'],['meat-seafood'],['stpp-vs-shmp',docs]),
 'sodium-trimetaphosphate-stmp':entry('Specify the reagent and the resulting starch separately',
  'Our STMP discussion concerns starch-modification processes. The cyclic phosphate reagent and the modified starch produced from it have different identities and qualification requirements; a reagent specification alone does not characterize the finished ingredient.',
  'STMP is distinct from tripolyphosphate and commercial SHMP. Selecting by similar initials can lead to the wrong raw material. Describe the intended starch modification and the required final starch identity in the inquiry.',
  'A process comparison should track starch source, treatment conditions and the relevant finished-starch identity and residual tests. Functional observations can then address the intended food’s viscosity, texture or stability requirements.',
  'Include the manufacturing process and raw-material handling requirements. Request the proposed reagent specification and SDS together with source-specific pack and storage information.',
  ['sodium-tripolyphosphate-stpp','sodium-hexametaphosphate-shmp'],['starch-processing'],[docs,'qualify-ingredient-source']),
 'monopotassium-phosphate-mkp':entry('Acidic phosphate input with potassium',
  'MKP combines potassium and phosphate in an acidic orthophosphate. Potential discussions include buffer systems, reconstituted mixtures and fermentation nutrient requirements. The food or process determines which composition and handling characteristics matter.',
  'Food and agricultural materials may share a chemical name while having different specifications and impurity controls. A fertilizer nutrient analysis cannot replace a specification for the intended food-processing use.',
  'For formulated foods, observe dissolution, pH and mineral interactions. For fermentation, compare the full nutrient system and the selected organism’s process requirements rather than treating phosphate concentration as a universal optimization target.',
  'State the intended use clearly on the inquiry. Ask for the proposed grade’s pack identification and storage information so that receiving records distinguish it from agricultural material.',
  ['dipotassium-phosphate-dkp','sodium-dihydrogen-phosphate-msp'],['beverages','fermentation'],[docs,brief]),
 'dipotassium-phosphate-dkp':entry('Buffer and mineral balance in protein-containing systems',
  'DKP is a potassium orthophosphate considered when buffer balance and mineral interactions are relevant. Dairy formulations, plant-based alternatives and beverage mixes can respond differently because their protein and mineral environments differ.',
  'DKP is not interchangeable with MKP or TKP by equal mass. Hydration form, assay reporting basis and pH preparation conditions also affect how two DKP specifications can be compared.',
  'Use the actual protein source, calcium and other salts, heat treatment and water quality. Observe separation, sediment, texture and taste alongside pH.',
  'Tell us whether the product enters a powder blend or a liquid preparation step. Include the required hydration form and ask about packing, storage and shelf-life information for that material.',
  ['monopotassium-phosphate-mkp','tripotassium-phosphate-tkp','disodium-phosphate-dsp'],['dairy','beverages'],[docs,brief]),
 'tripotassium-phosphate-tkp':entry('Potassium-based alkaline phosphate systems',
  'TKP is the more alkaline member of the potassium orthophosphate group. Its contribution must be considered alongside the formula’s other acids, salts and minerals, especially where a narrow pH response or sensory profile matters.',
  'The exact hydration state and reporting basis are part of the grade description. A potassium-content objective does not make MKP, DKP and TKP equivalent alternatives.',
  'Compare pH response after each relevant process stage and observe precipitation, protein behavior and taste. Keep the addition sequence and preparation water consistent.',
  'Specify the physical form, handling route and destination market. Ask for source-specific safety, packaging and storage information as part of the quotation discussion.',
  ['dipotassium-phosphate-dkp','monopotassium-phosphate-mkp','trisodium-phosphate-tsp'],['beverages'],[docs,brief]),
 'tetrapotassium-pyrophosphate-tkpp':entry('Potassium pyrophosphate in a complete salt system',
  'TKPP offers a potassium-based pyrophosphate direction for food-system comparisons. Replacing a sodium phosphate changes more than the cation: pH, dissolution and the full mineral balance need to be evaluated together.',
  'TKPP is distinct from tripotassium phosphate and potassium tripolyphosphate. Compare the exact identity, analytical basis and physical grade rather than selecting by the shared potassium-phosphate wording.',
  'Prepare comparable solutions or mixes and record clarity, pH and undissolved material. Evaluate the complete food for texture, separation and sensory changes under the same processing conditions.',
  'Include the preparation temperature, dry or liquid addition route and required quantity. Ask for the offered source’s pack, sample and storage terms with its specification.',
  ['tetrasodium-pyrophosphate-tspp','potassium-tripolyphosphate-ktpp','tripotassium-phosphate-tkp'],['meat-seafood','dairy'],[docs,'stpp-vs-shmp']),
 'potassium-tripolyphosphate-ktpp':entry('A potassium tripolyphosphate comparison',
  'KTPP provides a different phosphate identity from potassium orthophosphates or TKPP. Where a potassium-based phosphate is being considered, the comparison should cover composition, pH contribution and process behavior together.',
  'A switch from STPP to KTPP is not an equal-mass performance guarantee. Keep phosphate expression separate from potassium content, and compare dissolution and particle characteristics for the actual commercial grades.',
  'In a protein-food trial, retain the same raw material, salt and processing schedule. Follow pH, texture, separation and relevant cooking or thawing observations against the existing phosphate system.',
  'Describe the proposed replacement and current incorporation step. Request grade-specific packaging and handling instructions, plus the sample and order terms for the offered source.',
  ['sodium-tripolyphosphate-stpp','tetrapotassium-pyrophosphate-tkpp'],['meat-seafood'],['stpp-vs-shmp',docs]),
 'potassium-metaphosphate-kmp':entry('Polymeric phosphate behavior matters',
  'Potassium metaphosphate requires attention to polymeric identity and preparation behavior. It should not be treated as a readily soluble potassium orthophosphate simply because both materials contain potassium and phosphate.',
  'A useful grade description includes how the material is dispersed or prepared for analysis. A pH or viscosity result without that preparation context is a poor basis for comparing two products.',
  'Record the medium, addition order, temperature, mixing and elapsed time. Compare dispersed or undispersed material and the finished system’s appearance before interpreting a numerical result.',
  'Include the intended processing route and required physical form. Ask for relevant preparation guidance and source-specific packaging and storage information with the product records.',
  ['sodium-hexametaphosphate-shmp','monopotassium-phosphate-mkp'],['beverages'],[docs,'qualify-ingredient-source']),
 'monocalcium-phosphate-mcp':entry('Monohydrate MCP in leavening selection',
  'Monocalcium phosphate monohydrate is an acid-phosphate direction for chemical leavening. Selection connects the acid component to bicarbonate, mixing, holding and heating, rather than relying on the MCP abbreviation alone.',
  'Monohydrate and anhydrous MCP are separate materials. The water incorporated in the material and its commercial reaction characteristics both matter to a recipe comparison; calcium content alone is not a reaction-rate specification.',
  'Compare acid–bicarbonate balance and the actual mix-to-bake interval. Observe batter or dough pH, rise, crumb and taste with the same ingredients and heating schedule.',
  'Name the monohydrate explicitly when requesting a sample or quotation. Include dry-mix handling conditions and ask for the corresponding pack and source storage instructions.',
  ['monocalcium-phosphate-anhydrous','sodium-acid-pyrophosphate-sapp'],['bakery'],['sapp-vs-salp-bakery',docs]),
 'monocalcium-phosphate-anhydrous':entry('Anhydrous MCP as its own commercial grade',
  'Anhydrous MCP belongs in the leavening discussion as a distinct material. Its practical behavior depends on the commercial grade and the food process, not simply on the absence of water in the name.',
  'Do not use a monohydrate specification to describe an anhydrous order. Composition basis, water-related tests and reaction information must correspond to the actual grade being compared.',
  'Use the same acid–bicarbonate calculation basis and record holding and heating conditions. Examine pH, gas development and the finished baked structure instead of assuming anhydrous always means a particular reaction speed.',
  'State anhydrous MCP in the inquiry and sample identification. Discuss handling before blending, pack format and storage requirements using that source’s records.',
  ['monocalcium-phosphate-mcp','sodium-acid-pyrophosphate-sapp'],['bakery'],['sapp-vs-salp-bakery',docs]),
 'dicalcium-phosphate-dcp':entry('Anhydrous calcium hydrogen phosphate',
  'DCP anhydrous can enter discussions about calcium-phosphate composition and particulate behavior in foods or premixes. The required function should guide the specification: mineral composition and dispersion are different purchasing questions.',
  'Anhydrous DCP and DCP dihydrate differ in hydration and mass basis. An anhydrous-basis assay does not, by itself, prove that a delivered material is physically anhydrous.',
  'Compare particle behavior, dispersion and visible sediment in the intended system. Keep water chemistry and processing consistent, and use the relevant composition basis for any formulation calculation.',
  'Specify the anhydrous form, particle requirements and dry-blending or dispersion route. Request the source’s pack, label, storage and shelf-life details for that form.',
  ['dicalcium-phosphate-dihydrate','tricalcium-phosphate-tcp'],['mineral-formulation'],[docs,brief]),
 'dicalcium-phosphate-dihydrate':entry('Dihydrate DCP with a defined water basis',
  'Dicalcium phosphate dihydrate has its own hydration identity and composition basis. It belongs in a mineral-ingredient comparison as the dihydrate, rather than as an unspecified DCP substitute.',
  'The water associated with the dihydrate affects calculations and interpretation of heating tests. Separate hydration identity, assay basis and particle characteristics when reviewing a candidate grade.',
  'Compare the intended food or premix using consistent dispersion and sampling. Record sediment, blend distribution or texture where relevant, and do not infer equal-mass equivalence to the anhydrous form.',
  'Name the dihydrate on the inquiry and request matching sample and pack identification. Obtain storage and shelf-life instructions for the specific source and material.',
  ['dicalcium-phosphate-dcp','tricalcium-phosphate-tcp'],['mineral-formulation'],[docs,brief]),
 'tricalcium-phosphate-tcp':entry('Calcium phosphate composition and powder behavior',
  'TCP is a calcium-phosphate direction for mineral and powder-system discussions. Its low water solubility makes particle characteristics and dispersion important when assessing a liquid food; in a powder, flow and blend distribution may be more relevant.',
  'Commercial calcium-phosphate composition needs a clear analytical expression. Calcium, phosphate reported as P₂O₅ and an assay field should not be treated as interchangeable percentages.',
  'For a powder, observe blending and segregation under the intended handling conditions. For a dispersed system, observe sediment, texture and appearance with the actual mixing and storage sequence.',
  'Describe the physical form and receiving or blending equipment. Request the proposed particle specification and source-specific pack and storage information with the commercial offer.',
  ['dicalcium-phosphate-dcp','dicalcium-phosphate-dihydrate'],['mineral-formulation'],[docs,brief]),
 'monoammonium-phosphate-map':entry('Acidic ammonium phosphate for nutrient-system discussion',
  'MAP brings ammonium and phosphate to a nutrient-system comparison. For fermentation-related inquiries, the organism, medium and intended process result determine whether this input is relevant.',
  'MAP and DAP have different ammonium-to-phosphate composition and acid-base behavior. Their common family name does not support an equal-mass substitution or a common specification.',
  'Compare the complete nutrient and pH-control system under a qualified process plan. Track process response and the intended product’s quality rather than assuming that more nutrient necessarily improves the result.',
  'State the food-processing use, material identity and required documents. Request packing, storage and sample terms for the exact proposed grade; agricultural descriptions are not sufficient for a food-processing purchase.',
  ['diammonium-phosphate-dap','monopotassium-phosphate-mkp'],['fermentation'],[docs,brief]),
 'diammonium-phosphate-dap':entry('Ammonium and phosphate balance in fermentation inputs',
  'DAP is a distinct nutrient-system candidate from MAP. Its ammonium and phosphate contribution should be evaluated against the complete fermentation medium and the intended organism and process.',
  'A nitrogen-content target does not fully define DAP suitability. Identity, grade, composition basis and impurities remain separate requirements, and a similar nutrient claim on an agricultural product does not establish food-processing suitability.',
  'Compare nutrient balance and pH behavior while holding the process conditions consistent. A qualified technical team should define the relevant process observations and finished-product checks.',
  'Include the intended process and required material grade in the request. Ask for source-specific pack identification, storage and shelf-life records with the commercial terms.',
  ['monoammonium-phosphate-map','monopotassium-phosphate-mkp'],['fermentation'],[docs,brief]),
 'food-phosphate-blends':entry('Start a blend inquiry with the food system',
  'Our phosphate-blend discussions are organized around meat and seafood, dairy and prepared foods, and bakery systems. These application directions describe the purchasing problem; they are not fixed formulas or named commercial models.',
  'A blend is defined by its components and actual commercial grade. A meat-water-management blend and a bakery leavening-acid blend may have very different purposes. A single CAS number, assay or phosphate percentage cannot identify every mixture.',
  'Compare an identified candidate with the existing formulation under the same process. For meat or seafood, distinguish uptake from retained moisture; for dairy foods, track separation and texture; for bakery, follow acid–bicarbonate balance and holding behavior.',
  'Send the application, process, target function, volume and market. Ask for the proposed blend designation, composition information, pack format and source-specific storage terms; any sample evaluation should refer to that same grade.',
  ['sodium-tripolyphosphate-stpp','tetrasodium-pyrophosphate-tspp','sodium-acid-pyrophosphate-sapp'],['meat-seafood','dairy','bakery'],[docs,brief]),
 'sodium-aluminum-phosphate-salp':entry('Acidic SALP for a defined baking system',
  'This product discussion focuses on acidic SALP used as a leavening-acid direction. It should be considered together with bicarbonate, batter or dough composition and the actual holding and heating schedule.',
  'The name SALP alone does not resolve every chemical or commercial grade. Acidic and basic sodium aluminum phosphate should not share one specification, and a chemical assay does not describe the complete reaction profile.',
  'Compare the identified acidic grade against the current leavening system. Observe pH, rise, crumb and taste while keeping acid–bicarbonate balance and the process schedule explicit.',
  'Identify the acidic commercial grade and destination market in the inquiry. Ask for its specification, sample terms and source-specific pack and storage information before discussing an order.',
  ['sodium-acid-pyrophosphate-sapp','monocalcium-phosphate-mcp'],['bakery'],['sapp-vs-salp-bakery',docs])
};

export function phosphateSelection(product,e){
 const d=phosphateDetails[product.slug];if(!d)return '';
 return `<section class="product-section page-section" id="grade-selection"><div class="container"><div class="section-kicker">GRADE & PROCESS</div><h2>${e(d.heading)}</h2><div class="phosphate-detail-grid"><div><h3>Choosing the material</h3><p>${e(d.forms)}</p></div><div><h3>Planning a useful comparison</h3><p>${e(d.trial)}</p></div></div></div></section>`;
}
