// Catalogue identities and purchasing content, not supplied specifications.
// Evidence and unresolved source questions: internal PHOSPHATE-CATALOG-PLAN.md.
export const phosphateFamilies = [
 ['Sodium Phosphates','Compare orthophosphates, pyrophosphates and condensed phosphates by identity, form and intended function.'],
 ['Potassium Phosphates','Distinguish potassium orthophosphates from pyro-, tripoly- and metaphosphates before comparing grades.'],
 ['Calcium Phosphates','Choose the calcium phosphate identity and hydration form before comparing mineral content or processing behavior.'],
 ['Phosphate Blends','Describe the food and process when discussing a blend. Composition and commercial grade must match the proposed application.'],
 ['Ammonium Phosphates','Compare ammonium and phosphate contribution, acidity and the requirements of the intended process.'],
 ['Other Phosphates','Sodium aluminum phosphate has a distinct identity; compare its specific commercial grade for the intended leavening system.']
];
export const existingPhosphateFamilies = {
 'sodium-tripolyphosphate-stpp':'Sodium Phosphates',
 'sodium-hexametaphosphate-shmp':'Sodium Phosphates',
 'sodium-acid-pyrophosphate-sapp':'Sodium Phosphates',
 'tetrapotassium-pyrophosphate-tkpp':'Potassium Phosphates',
 'sodium-aluminum-phosphate-salp':'Other Phosphates'
};
const monograph = (id,label) => [label,`https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-${id}.pdf`];
const identityRecord = (id,label) => [label,`https://www.fao.org/food/food-safety-quality/scientific-advice/jecfa/jecfa-additives/detail/en/c/${id}/`];
const sourceQuestion = ['What should accompany my inquiry?','Include the exact material and form, food application, destination market and target specification. Request current records for the proposed grade and source, and identify any methods your quality team requires.'];
const record = (product,procurement) => ({...product,procurement:{...procurement,faqs:[...procurement.faqs,sourceQuestion]}});
export const phosphateEntries = [
 record({slug:'sodium-dihydrogen-phosphate-msp',name:'Sodium Dihydrogen Phosphate',abbr:'MSP',family:'Sodium Phosphates',
  lead:'An acidic sodium orthophosphate for buffering and phosphate-system comparisons.',
  role:'MSP differs from disodium and trisodium phosphate in acid-base behavior. Identify the hydration form and assess the full buffer system before comparing quantities.',
  uses:['Buffer systems: compare pH response alongside the other acid and salt components.','Mineral-sensitive foods: assess clarity, sediment and protein response in the complete formulation.'],
  checks:['Specify anhydrous, monohydrate or dihydrate material.','Compare assay on the same reporting basis and pH under the same preparation conditions.'],
  question:'Which hydration form and finished-food pH behavior do you need?'},
 {aliases:['Monosodium phosphate','Sodium phosphate monobasic','Sodium dihydrogen orthophosphate'],
  identity:'Sodium dihydrogen phosphate is monosodium phosphate, an orthophosphate distinct from DSP and TSP. Anhydrous and hydrated materials require their own form identification.',
  grade:'State the hydration form on the request and specification. Water of crystallization changes the mass basis; a common abbreviation is insufficient for a like-for-like comparison.',
  parameters:[['Form and assay basis','Salt identity, hydration and assay method','Named hydrate; stated mass basis','Keep form-dependent values separate.'],['Solution pH','Sample concentration, water and temperature','pH with preparation conditions','Compare buffer ingredients using equivalent tests.'],['Purity and insolubles','Current impurity limits and methods','Source-defined units and method','Match the intended grade and quality review.']],
  documents:'Form-specific specification, current TDS and representative COA; confirm availability',
  faqs:[['Is MSP interchangeable with DSP?','No. Their acid-base behavior and sodium contribution differ. Compare the complete buffer recipe and the required hydration form.']],references:[identityRecord('202','FAO/JECFA — Sodium dihydrogen phosphate identity')]}),
 record({slug:'disodium-phosphate-dsp',name:'Disodium Phosphate',abbr:'DSP',family:'Sodium Phosphates',
  lead:'A sodium orthophosphate considered for buffering and mineral balance in formulated foods.',
  role:'DSP is disodium hydrogen phosphate. Its hydration form and analytical basis need to match the recipe and the offered specification.',
  uses:['Dairy or emulsifying-salt systems: observe protein response, texture and separation.','Buffer formulations: compare pH response with the complete acid and mineral system.'],
  checks:['Identify the actual hydrate instead of ordering by DSP alone.','Separate loss on drying from assay and confirm the test conditions.'],
  question:'Is the objective buffer response, mineral balance or a defined emulsifying-salt system?'},
 {aliases:['Disodium hydrogen phosphate','Sodium phosphate dibasic','Dibasic sodium phosphate'],
  identity:'Disodium phosphate is disodium hydrogen phosphate, a sodium orthophosphate available in different hydration forms. The form must be named when matching the specification and sample.',
  grade:'Compare assay, water-related measurements and the recipe mass basis for the selected hydrate. Results for different forms should not be merged into one acceptance table.',
  parameters:[['Hydration form','Exact hydrate and identity statement','Named form','Distinguish anhydrous and hydrated offers.'],['Assay and water loss','Analytical basis, drying temperature and duration','Mass basis and test conditions','Avoid treating water of crystallization as contamination.'],['Buffer response','Solution pH method and intended food pH','pH under stated conditions','A raw-material solution test is not the food response.']],
  documents:'Hydrate-specific specification, drying method and representative COA; confirm availability',
  faqs:[['Can all DSP grades share one specification?','No. Name the hydrate and compare the corresponding assay basis and water-loss method before agreeing limits.']],references:[identityRecord('81','FAO/JECFA — Disodium hydrogen phosphate identity')]}),
 record({slug:'trisodium-phosphate-tsp',name:'Trisodium Phosphate',abbr:'TSP',family:'Sodium Phosphates',
  lead:'An alkaline sodium orthophosphate for application-specific pH and mineral-system evaluation.',
  role:'TSP contributes alkalinity and sodium as well as phosphate. The full recipe, hydration form and handling requirements govern its selection.',
  uses:['Buffer and mineral systems: measure pH response and interactions in the food.','Protein or emulsifying-salt formulations: compare texture, separation and sensory effects under controlled conditions.'],
  checks:['Distinguish anhydrous material from dodecahydrate and other declared forms.','Review concentration, addition sequence, finished pH and the applicable handling information.'],
  question:'Which form and alkalinity target are specified for your process?'},
 {aliases:['Sodium phosphate tribasic','Tribasic sodium phosphate','Trisodium orthophosphate'],
  identity:'Trisodium phosphate is an alkaline sodium orthophosphate. Anhydrous and hydrated forms, including dodecahydrate, have different water content and formulation mass bases.',
  grade:'Select the form before comparing assay and drying data. Trial the alkalinity in the actual recipe, including taste and protein response, rather than substituting by name alone.',
  parameters:[['Identity and hydrate','Exact form and declared composition','Named form','Avoid mixing anhydrous and hydrate data.'],['Assay and drying','Basis, method and drying conditions','Source-defined mass basis','Water loss must correspond to the named material.'],['pH and handling','Concentration for pH testing and current SDS','pH; handling instructions','Relate alkalinity to process control and safe handling.']],
  documents:'Form-specific specification, SDS and representative COA; confirm availability',
  faqs:[['Is TSP the same as STPP?','No. TSP is an orthophosphate and STPP is a tripolyphosphate. Compare identity, acid-base behavior and the intended function separately.']],references:[identityRecord('451','FAO/JECFA — Trisodium phosphate identity')]}),
 record({slug:'tetrasodium-pyrophosphate-tspp',name:'Tetrasodium Pyrophosphate',abbr:'TSPP',family:'Sodium Phosphates',
  lead:'An alkaline pyrophosphate considered for buffering, mineral interactions and emulsifying-salt systems.',
  role:'TSPP is distinct from acidic SAPP and from STPP. Hydration, dissolution and the salt/protein system matter when assessing an offered grade.',
  uses:['Protein foods: compare pH, texture, purge and cooking behavior in the same process.','Emulsifying-salt systems: observe mineral/protein interactions, separation and set.'],
  checks:['Specify anhydrous or hydrated material and its assay basis.','Agree pH preparation, dissolution conditions and relevant impurity methods.'],
  question:'Which hydration form, mixing process and food-system response are you comparing?'},
 {aliases:['Tetrasodium diphosphate','Sodium pyrophosphate','Sodium diphosphate tetrabasic'],
  identity:'Tetrasodium pyrophosphate is an alkaline diphosphate. Anhydrous and decahydrate forms require separate specifications; neither should be confused with sodium acid pyrophosphate.',
  grade:'Specify the exact form, assay basis and dissolution needs. Compare a proposed grade under the same water, salt, temperature and mixing conditions as the existing material.',
  parameters:[['Form and assay','Hydrate, analyte and reporting basis','Named form; analytical method','Do not transfer limits between hydration forms.'],['Alkalinity and dissolution','pH preparation and dissolution test','Concentration, temperature and time','Assess incorporation before comparing food performance.'],['Purity','Current impurity limits and test methods','Source-specific units and methods','Review the complete specification, not assay alone.']],
  documents:'Hydration-specific specification, TDS, analytical methods and representative COA; confirm availability',
  faqs:[['Can TSPP replace SAPP in a leavening system?','Do not substitute on the pyrophosphate name. TSPP and SAPP have different acid-base roles; the complete acid–bicarbonate system needs its own design and trials.']],references:[monograph('461','FAO/JECFA — Tetrasodium pyrophosphate identity and forms')]}),
 record({slug:'sodium-trimetaphosphate-stmp',name:'Sodium Trimetaphosphate',abbr:'STMP',family:'Sodium Phosphates',
  lead:'A cyclic condensed phosphate for process-specific discussion in starch modification.',
  role:'STMP is chemically distinct from STPP and commercial SHMP. Its use in a starch-modification process requires evaluation of both the reagent and resulting modified starch.',
  uses:['Starch modification: define the starch source, reaction process and intended modified-starch identity.','Process qualification: identify the required reagent purity, residual controls and finished-starch tests.'],
  checks:['Distinguish process reagent qualification from direct addition to finished food.','Review the intended process and destination-market requirements before selecting a grade.'],
  question:'Are you specifying a reagent for starch modification, and what finished-starch identity is required?'},
 {aliases:['Trisodium trimetaphosphate','Sodium trimetaphosphate cyclic'],
  identity:'Sodium trimetaphosphate is a cyclic condensed phosphate. It is not another name for sodium tripolyphosphate or for the commercial polyphosphate glass commonly called SHMP.',
  grade:'Define the process and resulting material before discussing grade requirements. A reference to modified-starch manufacture is not a general permission to add STMP directly to foods.',
  parameters:[['Reagent identity','Exact material and purity method','Named reagent; method','Prevent confusion between condensed phosphates.'],['Process requirements','Starch source, intended modification and impurity controls','Process specification','Link material selection to the manufacturing purpose.'],['Finished-starch evidence','Required identity and residual/quality tests','Applicable methods','Reagent purity alone does not qualify the finished starch.']],
  documents:'Reagent specification, SDS and process-relevant source records; confirm availability',
  faqs:[['Should I use STMP like a general food buffer?','The discussion here concerns starch-modification processes. Direct food addition needs a separate technical and destination-market review.']],references:[['FAO/JECFA — Modified starches: modification routes','https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/monograph16/additive-287-m16.pdf']]}),
 record({slug:'monopotassium-phosphate-mkp',name:'Monopotassium Phosphate',abbr:'MKP',family:'Potassium Phosphates',
  lead:'An acidic potassium orthophosphate for buffer and nutrient-system comparisons.',
  role:'MKP is potassium dihydrogen phosphate. Its acid-base contribution differs from DKP and TKP, even though all belong to the potassium orthophosphate family.',
  uses:['Buffer systems: compare the complete acid/salt balance and finished pH.','Fermentation-related requirements: specify the intended potassium and phosphate contribution and process conditions.'],
  checks:['Request a specification for the intended food or processing grade.','Compare assay basis, pH preparation, impurities and dissolution conditions.'],
  question:'Which buffer response or potassium/phosphate requirement drives the inquiry?'},
 {aliases:['Potassium dihydrogen phosphate','Potassium phosphate monobasic','Monobasic potassium phosphate'],
  identity:'Monopotassium phosphate is potassium dihydrogen phosphate, a potassium orthophosphate. It is distinct from dipotassium and tripotassium phosphate in both identity and acid-base contribution.',
  grade:'A chemical name shared with agricultural or industrial material does not identify a suitable food grade. Review the actual source specification and requirements for the intended use.',
  parameters:[['Identity and assay','Material identity and assay basis','Analytical method and basis','Distinguish MKP from other potassium salts.'],['pH and dissolution','Preparation, concentration and temperature','pH; dissolution conditions','Compare buffering ingredients under equivalent conditions.'],['Purity','Impurity limits and analytical methods','Source-defined units','Match the intended grade and market review.']],
  documents:'Current grade-specific specification, relevant TDS and representative COA; confirm availability',
  faqs:[['Can MKP and DKP be exchanged on equal mass?','No. Compare their acid-base and mineral contributions in the complete formulation before deciding a substitution.']],references:[monograph('336','FAO/JECFA — Potassium dihydrogen phosphate')]}),
 record({slug:'dipotassium-phosphate-dkp',name:'Dipotassium Phosphate',abbr:'DKP',family:'Potassium Phosphates',
  lead:'A potassium orthophosphate considered for buffering and mineral balance.',
  role:'DKP is dipotassium hydrogen phosphate. Choose the declared hydration form and compare pH behavior within the complete food, rather than relying on a solution value alone.',
  uses:['Dairy and plant-based formulations: compare protein response, sediment and heat-process behavior.','Buffer systems: measure pH response together with other acids, salts and minerals.'],
  checks:['Identify the form and match the assay and water-loss basis.','Review pH test concentration and the actual protein/mineral system.'],
  question:'What food composition and heating conditions should the selected grade be assessed against?'},
 {aliases:['Dipotassium hydrogen phosphate','Potassium phosphate dibasic','Dibasic potassium phosphate'],
  identity:'Dipotassium phosphate is dipotassium hydrogen phosphate. Anhydrous and hydrated descriptions must be resolved against the offered specification rather than inferred from the abbreviation DKP.',
  grade:'Compare hydration, assay basis and pH test conditions together. In protein-containing foods, include the actual protein source, mineral load, heat treatment and observed instability.',
  parameters:[['Form and assay','Hydrate and analytical basis','Named form; assay method','Keep the sample and specification aligned.'],['pH','Test concentration, water and temperature','pH with method','A powder specification cannot predict the food pH alone.'],['Insolubles and purity','Methods and current limits','Source-defined units','Relate clarity and quality requirements to the offered grade.']],
  documents:'Hydrate-specific specification, TDS and representative COA; confirm availability',
  faqs:[['Does DKP automatically stabilize a dairy or plant-based beverage?','No. Protein type, minerals, pH, heating and the complete formulation determine the result. Compare sediment and separation with a control.']],references:[monograph('162','FAO/JECFA — Dipotassium hydrogen phosphate')]}),
 record({slug:'tripotassium-phosphate-tkp',name:'Tripotassium Phosphate',abbr:'TKP',family:'Potassium Phosphates',
  lead:'An alkaline potassium orthophosphate for defined buffering and mineral-system requirements.',
  role:'TKP contributes potassium and alkalinity. Select it by the intended function and exact form, with attention to handling and finished-food pH.',
  uses:['Buffer systems: evaluate pH response and sensory effects in the complete formulation.','Emulsifying-salt discussions: compare protein/mineral response under the actual heating and mixing conditions.'],
  checks:['State the hydrate and the assay or water-loss basis.','Distinguish TKP from TKPP and KTPP when preparing a request.'],
  question:'What alkalinity, hydration form and potassium contribution are needed?'},
 {aliases:['Tribasic potassium phosphate','Potassium phosphate tribasic','Tripotassium orthophosphate'],
  identity:'Tripotassium phosphate is a potassium orthophosphate with alkaline behavior. Its anhydrous or hydrated form must be specified, and it is distinct from potassium pyro- and tripolyphosphates.',
  grade:'Review the declared hydration and analytical basis before comparing offers. Assess pH, taste and food-system response at the intended processing conditions instead of using alkalinity alone.',
  parameters:[['Hydrate and assay','Exact form and reporting basis','Named form; method','Separate water of crystallization from assay.'],['Water-related tests','Drying or ignition method and conditions','Temperature, duration and basis','Avoid combining different methods into one limit.'],['pH and handling','Preparation for pH measurement and SDS','Concentration and handling guidance','Account for alkalinity during incorporation.']],
  documents:'Form-specific specification, water-loss methods, SDS and representative COA; confirm availability',
  faqs:[['How do TKP, TKPP and KTPP differ?','They are orthophosphate, pyrophosphate and tripolyphosphate respectively. Each needs its own identity, specification and functional comparison.']],references:[monograph('480','FAO/JECFA — Tripotassium phosphate forms')]}),
 record({slug:'potassium-tripolyphosphate-ktpp',name:'Potassium Tripolyphosphate',abbr:'KTPP',family:'Potassium Phosphates',
  lead:'A potassium triphosphate for texture-related and mineral-system comparisons.',
  role:'KTPP is pentapotassium triphosphate. The offered composition, dissolution behavior and potassium contribution matter when comparing it with other condensed phosphates.',
  uses:['Texture-focused formulations: compare behavior in the complete food and processing sequence.','Potassium-based phosphate systems: assess mineral contribution together with pH and sensory results.'],
  checks:['Distinguish triphosphate assay from total phosphorus reporting.','Request the source composition, insolubles and dissolution method.'],
  question:'Are you comparing phosphate identity, potassium contribution or a texture outcome?'},
 {aliases:['Pentapotassium triphosphate','Pentapotassium tripolyphosphate','Potassium triphosphate'],
  identity:'Potassium tripolyphosphate is pentapotassium triphosphate, a condensed phosphate distinct from TKP and TKPP. A commercial specification should identify the assay basis and other phosphate components.',
  grade:'Compare composition and analytical basis before a formulation trial. A potassium-based identity does not establish an equal-mass replacement for a sodium phosphate or a nutritional label claim.',
  parameters:[['Triphosphate assay','Identity, method and reporting basis','Analyte and mass basis','Distinguish triphosphate from total phosphate.'],['Total phosphorus','Declared expression and method','P or oxide-equivalent basis','Use a consistent mineral calculation.'],['Dissolution and pH','Insolubles and preparation conditions','Temperature, concentration and method','Relate laboratory readings to incorporation.']],
  documents:'Current composition/specification, TDS and representative COA; confirm availability',
  faqs:[['Does replacing STPP with KTPP guarantee equivalent texture?','No. Compare phosphate composition, mineral balance, pH, dissolution and the finished-food response under matched process conditions.']],references:[monograph('307','FAO/JECFA — Pentapotassium triphosphate identity')]}),
 record({slug:'potassium-metaphosphate-kmp',name:'Potassium Metaphosphate',abbr:'KMP',family:'Potassium Phosphates',
  lead:'A polymeric potassium phosphate requiring grade-specific dispersion and preparation information.',
  role:'The metaphosphate name does not define a single interchangeable grade. Identify the polymeric material and the preparation used for its viscosity, pH or dispersion measurements.',
  uses:['Phosphate-system comparisons: define the intended textural or mineral-related function.','Processing trials: assess dispersion and interaction with the actual salts and food matrix.'],
  checks:['Ask how the material is characterized and how test samples are prepared.','Do not assume the dissolution behavior of MKP, DKP or KTPP applies.'],
  question:'Which preparation method and food-system response are required for this polymeric grade?'},
 {aliases:['Potassium polymetaphosphate','Potassium polyphosphate','Potassium polyphosphates'],
  identity:'Potassium metaphosphate is a name used for polymeric potassium phosphates. The commercial material needs a defined identity and characterization, rather than an assumed fixed small-molecule composition.',
  grade:'Request the preparation method for pH, viscosity and dispersion measurements. A number without solution or dispersion conditions is not a useful basis for comparing polymeric grades.',
  parameters:[['Polymeric identity','Composition and grade characterization','Source-defined identity','Distinguish the proposed polymeric material.'],['Dispersion and viscosity','Preparation, medium, temperature and instrument','Method-specific units','Avoid comparing unlike preparations.'],['Phosphate and purity','Assay expression, insolubles and impurity methods','Stated basis and methods','Connect analytical data to the defined grade.']],
  documents:'Grade characterization, preparation methods, current TDS and specification; confirm availability',
  faqs:[['Can KMP be treated like a readily soluble orthophosphate?','Do not assume equivalent behavior. Obtain grade-specific preparation and dispersion information and evaluate the actual formulation.']],references:[['WHO/JECFA — Potassium polyphosphates terminology','https://apps.who.int/food-additives-contaminants-jecfa-database/Home/Chemical/2400']]}),
 record({slug:'monocalcium-phosphate-mcp',name:'Monocalcium Phosphate Monohydrate',abbr:'MCP monohydrate',family:'Calcium Phosphates',
  lead:'The monohydrate form of calcium dihydrogen phosphate for leavening-system comparisons.',
  role:'MCP monohydrate can be evaluated as an acid component with bicarbonate. Hydration form, commercial grade and reaction testing all matter to a bakery request.',
  uses:['Bakery systems: compare batter holding, gas release, finished pH and crumb.','Dry premixes: assess particle distribution and storage-related blend behavior.'],
  checks:['Name the monohydrate rather than an unspecified MCP.','Request neutralizing and reaction-test methods for the commercial grade.'],
  question:'What holding time and heating profile must the leavening system accommodate?'},
 {aliases:['MCP','Calcium dihydrogen phosphate monohydrate','Monobasic calcium phosphate monohydrate'],
  identity:'Monocalcium phosphate monohydrate is the hydrated form of calcium dihydrogen phosphate. It has a distinct formulation mass basis from the anhydrous material and needs a form-specific specification.',
  grade:'The monohydrate identity alone does not define a reaction curve. Compare the commercial grade with the full bicarbonate system, holding period and thermal process.',
  parameters:[['Hydrate and assay','Monohydrate identity and assay basis','Named form; method','Keep hydrated and anhydrous records separate.'],['Leavening behavior','Neutralizing value and reaction-test definition','Supplier-defined method','Compare balance separately from reaction timing.'],['Particle and moisture','Sieve profile and water-loss method','Method and conditions','Relate mixing and storage to the intended premix.']],
  documents:'Monohydrate specification, leavening-grade TDS and representative COA; confirm availability',
  faqs:[['Can an anhydrous MCP specification cover this form?','No. Ask for records naming the monohydrate. Compare recipe calculations and commercial reaction behavior before considering a change of form.']],references:[monograph('080','FAO/JECFA — Calcium dihydrogen phosphate forms')]}),
 record({slug:'monocalcium-phosphate-anhydrous',name:'Monocalcium Phosphate Anhydrous',abbr:'MCP anhydrous',family:'Calcium Phosphates',
  lead:'The anhydrous form of calcium dihydrogen phosphate for grade-specific bakery and premix evaluation.',
  role:'Anhydrous MCP has its own material basis. Reaction behavior depends on the commercial grade and full leavening system, not just the absence of water of crystallization.',
  uses:['Bakery mixes: compare leavening balance, waiting time and oven response.','Dry formulations: evaluate incorporation, particle segregation and moisture sensitivity.'],
  checks:['Specify anhydrous material consistently in the inquiry, sample and documents.','Compare the offered grade with a defined control in the complete recipe.'],
  question:'Is anhydrous MCP required by an existing specification or being compared with a monohydrate grade?'},
 {aliases:['Anhydrous monocalcium phosphate','Calcium dihydrogen phosphate anhydrous','MCP-A'],
  identity:'Monocalcium phosphate anhydrous is calcium dihydrogen phosphate without water of crystallization. It is maintained as a separate product identity from MCP monohydrate.',
  grade:'Request a specification explicitly naming the anhydrous form and the intended commercial leavening grade. Do not transfer monohydrate values or reaction expectations without evaluation.',
  parameters:[['Anhydrous identity','Named form, assay method and basis','Form-specific specification','Prevent substitution of hydrate records.'],['Reaction characteristics','Grade definition and leavening methods','Method-specific results','Separate chemical identity from baking behavior.'],['Particle and water-related tests','Particle method and moisture test conditions','Defined methods','Relate handling to the actual premix process.']],
  documents:'Anhydrous specification, commercial-grade TDS and representative COA; confirm availability',
  faqs:[['Does anhydrous automatically mean a particular reaction speed?','No. Request the commercial grade definition and test method, then compare performance with bicarbonate in your actual holding and heating cycle.']],references:[monograph('080','FAO/JECFA — Calcium dihydrogen phosphate forms')]}),
 record({slug:'dicalcium-phosphate-dcp',name:'Dicalcium Phosphate Anhydrous',abbr:'DCP anhydrous',family:'Calcium Phosphates',
  lead:'Anhydrous calcium hydrogen phosphate for mineral and process-specific food formulation review.',
  role:'DCP anhydrous differs from the dihydrate in water content and material basis. Particle characteristics and the food system matter alongside chemical identity.',
  uses:['Mineral formulations: compare calcium/phosphorus contribution and dispersion.','Dry foods and bakery systems: assess particle distribution, handling and the intended processing function.'],
  checks:['Name anhydrous DCP and match the assay basis.','Distinguish loss on drying from loss on ignition and request each method.'],
  question:'Which mineral calculation basis and particle characteristics does your formulation require?'},
 {aliases:['DCP','Calcium hydrogen phosphate anhydrous','Dibasic calcium phosphate anhydrous'],
  identity:'Dicalcium phosphate anhydrous is calcium hydrogen phosphate without water of crystallization. It requires different form-specific records from dicalcium phosphate dihydrate.',
  grade:'Compare particle properties, mineral analysis and test basis together. Drying and ignition are different measurements; the method must be specified before values are compared.',
  parameters:[['Form and mineral basis','Anhydrous identity and calcium/phosphorus methods','Named form; reporting basis','Use consistent formulation calculations.'],['Water and ignition loss','Separate methods and sample conditions','Temperature, duration and basis','Do not treat distinct loss tests as interchangeable.'],['Particle profile','Sieve or particle-distribution method','Method-specific units','Assess dispersion and dry-blend segregation.']],
  documents:'Anhydrous specification, particle data and representative COA; confirm availability',
  faqs:[['Can I accept a document labelled only DCP?','Ask it to identify the hydration form. Match the proposed material, assay basis and water-related methods before approving it.']],references:[monograph('085','FAO/JECFA — Calcium hydrogen phosphate forms')]}),
 record({slug:'dicalcium-phosphate-dihydrate',name:'Dicalcium Phosphate Dihydrate',abbr:'DCP dihydrate',family:'Calcium Phosphates',
  lead:'The dihydrate form of calcium hydrogen phosphate for form-specific mineral and processing requirements.',
  role:'Water of crystallization affects the material basis of DCP dihydrate. Specify this form separately from anhydrous DCP when comparing mineral contribution and analytical results.',
  uses:['Mineral premixes: compare composition, particle behavior and blend uniformity.','Food processing: assess the intended function with the actual pH, mixing and thermal conditions.'],
  checks:['Match the dihydrate identity on the specification and sample.','Review drying conditions, assay basis and physical properties together.'],
  question:'Does your current specification explicitly require DCP dihydrate?'},
 {aliases:['Calcium hydrogen phosphate dihydrate','Dibasic calcium phosphate dihydrate','DCPD'],
  identity:'Dicalcium phosphate dihydrate is calcium hydrogen phosphate containing two waters of crystallization. It is a separate material identity from anhydrous DCP, not merely another particle grade.',
  grade:'Use a dihydrate-specific specification and mineral calculation basis. Compare water-loss methods and physical characteristics without borrowing limits from an anhydrous sheet.',
  parameters:[['Dihydrate identity','Form-specific identity and assay basis','Named hydrate','Keep the supplied sample and record aligned.'],['Drying behavior','Temperature, duration and calculation basis','Defined method','Distinguish bound water from other water-related measurements.'],['Mineral and particle data','Calcium/phosphorus basis and particle method','Stated units and methods','Support premix calculation and dispersion review.']],
  documents:'Dihydrate-specific specification, test methods and representative COA; confirm availability',
  faqs:[['Is equal-mass replacement of anhydrous DCP appropriate?','Do not assume it. Recalculate on the relevant material basis and assess particle behavior and the finished-food result.']],references:[monograph('085','FAO/JECFA — Calcium hydrogen phosphate forms')]}),
 record({slug:'tricalcium-phosphate-tcp',name:'Tricalcium Phosphate',abbr:'TCP',family:'Calcium Phosphates',
  lead:'A calcium phosphate considered for dry-flow, buffering and mineral formulation requirements.',
  role:'Commercial TCP needs composition and particle characterization. Mineral contribution and behavior in a food cannot be inferred from the short name alone.',
  uses:['Dry foods and premixes: compare flow, caking and segregation under representative storage.','Mineral formulations: evaluate dispersion, sediment and sensory effects in the complete food.'],
  checks:['Distinguish calcium assay from a phosphate-equivalent assay.','Ask for particle data, water/ignition methods and current impurity limits.'],
  question:'Is dry-flow performance or mineral contribution the main objective?'},
 {aliases:['Calcium phosphate tribasic','Tricalcium orthophosphate','Tribasic calcium phosphate'],
  identity:'Tricalcium phosphate is a commercial calcium phosphate material whose composition and analytical basis require qualification. A calcium assay is not the same measurement as phosphate-equivalent content.',
  grade:'Compare composition, particle profile and application results together. In a liquid system, dispersion and sediment behavior need attention; a dry-flow result does not predict beverage stability.',
  parameters:[['Composition and assay','Declared analyte, method and reporting basis','Calcium or phosphate-equivalent basis','Do not compare unlike assay expressions.'],['Particle characteristics','Particle distribution and bulk behavior','Method-specific units','Relate flow and dispersion to the intended food.'],['Ignition and purity','Ignition method and impurity tests','Source-defined units and conditions','Match the complete specification rather than one headline value.']],
  documents:'Current composition specification, particle information and representative COA; confirm availability',
  faqs:[['Does TCP dissolve like a soluble phosphate buffer?','TCP is poorly soluble in water. Evaluate dispersion and sediment in the actual food, and choose the material according to the required function.']],references:[monograph('475','FAO/JECFA — Tricalcium phosphate identity and functions')]}),
 record({slug:'monoammonium-phosphate-map',name:'Monoammonium Phosphate',abbr:'MAP',family:'Ammonium Phosphates',
  lead:'Ammonium dihydrogen phosphate for defined nutrient and acidity-related process requirements.',
  role:'MAP differs from DAP in ammonium/phosphate balance and acid-base behavior. The required grade must correspond to the intended food or fermentation process.',
  uses:['Fermentation discussions: identify the nutrient objective, process and existing nutrient system.','Formulation review: compare pH behavior and phosphate contribution with the complete recipe.'],
  checks:['Separate food/process grade requirements from fertilizer-grade identity.','Request current composition, impurity and pH test information for the proposed source.'],
  question:'Which process, nutrient objective and destination market apply?'},
 {aliases:['Ammonium dihydrogen phosphate','Ammonium phosphate monobasic'],
  identity:'Monoammonium phosphate is ammonium dihydrogen phosphate. Its identity and acid-base contribution differ from diammonium phosphate, and the offered grade needs source-specific qualification.',
  grade:'Specify the intended use and quality requirements before comparing offers. Agricultural product descriptions do not establish a food or fermentation grade for the proposed source.',
  parameters:[['Identity and composition','Ammonium/phosphate expression and assay method','Declared analytes and basis','Connect the material to the nutrient objective.'],['pH','Preparation, concentration and temperature','pH with method','Compare MAP and DAP under matched conditions.'],['Purity and source','Current impurity specification and origin records','Methods and applicable limits','Qualify the intended grade rather than the abbreviation.']],
  documents:'Grade-specific specification, source statement and representative COA; confirm availability',
  faqs:[['Can MAP and DAP use the same purchase description?','No. State the exact salt, nutrient objective and pH requirements. They should have separate specifications and evaluation.']],references:[monograph('023','FAO/JECFA — Ammonium dihydrogen phosphate')]}),
 record({slug:'diammonium-phosphate-dap',name:'Diammonium Phosphate',abbr:'DAP',family:'Ammonium Phosphates',
  lead:'Diammonium hydrogen phosphate for source-qualified nutrient and buffering discussions.',
  role:'DAP contributes ammonium and phosphate with different acid-base behavior from MAP. Assess the actual process requirements and source grade before selecting a material.',
  uses:['Yeast and fermentation systems: define the nutrient target and process controls.','Buffer-related requirements: evaluate pH response with the complete acid and nutrient system.'],
  checks:['Confirm the exact grade and ammonium/phosphorus reporting basis.','Compare pH, impurities and current source documents separately from fertilizer uses.'],
  question:'What nutrient balance and process conditions does the proposed DAP need to support?'},
 {aliases:['Diammonium hydrogen phosphate','Ammonium phosphate dibasic'],
  identity:'Diammonium phosphate is diammonium hydrogen phosphate, an ammonium orthophosphate distinct from MAP. A source-specific specification is needed for the intended food or processing grade.',
  grade:'Compare ammonium and phosphate contribution with pH behavior in the actual process. A high assay statement alone does not resolve impurity requirements, grade or intended-use suitability.',
  parameters:[['Composition','Assay, nitrogen and phosphorus reporting basis','Declared analytes and methods','Separate purity from nutrient contribution.'],['Solution behavior','pH, dissolution and preparation conditions','Concentration and temperature','Evaluate the intended process rather than a name match.'],['Grade and impurities','Current limits, methods and source identity','Source-specific specification','Keep food/process review separate from agricultural use.']],
  documents:'Current grade-specific specification, relevant TDS and representative COA; confirm availability',
  faqs:[['Does DAP always improve fermentation?','No. Evaluate the complete nutrient system, process and intended outcome. Nutrient identity does not establish the result for every organism or food.']],references:[monograph('150-m1-corr','FAO/JECFA — Diammonium hydrogen phosphate')]}),
 record({slug:'food-phosphate-blends',name:'Food Phosphate Blends',abbr:'Phosphate blends',family:'Phosphate Blends',
  lead:'Application-led discussions of blended phosphate systems for meat, seafood, dairy and bakery requirements.',
  role:'A phosphate blend is defined by its components and commercial grade. The application name alone does not identify composition, proportions or an interchangeable product.',
  uses:['Meat and seafood: describe salt, pH, mixing or treatment, texture and moisture observations.','Dairy and prepared foods: describe proteins, minerals, heating and separation or texture targets.','Bakery: distinguish leavening-acid blends from other phosphate systems and state the bicarbonate balance and timing.'],
  checks:['Request the actual grade designation, component identities and relevant declarations.','Compare the blend with a defined benchmark under the same recipe and process.','Agree which specification and records relate to the proposed commercial material.'],
  question:'Which food, process and measurable result should the proposed blend be evaluated against?'},
 {aliases:['Blended food phosphates','Compound phosphates','Meat phosphate blend','Seafood phosphate blend','Dairy phosphate blend','Bakery phosphate blend'],
  identity:'Food phosphate blends are mixtures defined by their component ingredients and commercial grade. They do not have one universal formula, CAS number, composition or reaction profile.',
  grade:'Start with the application and request the actual proposed grade and composition information. A meat, dairy or bakery label describes a discussion area, not a fixed recipe or a guarantee of performance.',
  parameters:[['Components and grade','Commercial designation and component identities','Grade-specific composition statement','Identify the material behind an application label.'],['Analytical profile','Phosphate expression, pH and preparation methods','Declared basis and methods','Make comparison conditions explicit.'],['Processing behavior','Dissolution, dispersion or reaction tests as relevant','Food/process-specific protocol','Choose tests that answer the actual application question.'],['Source and records','Specification revision, relevant declarations and batch record scope','Named source and revision','Tie sample and order review to the same material.']],
  documents:'Proposed blend designation, composition statement, specification, relevant TDS and representative COA; confirm availability',
  faqs:[['Does a blend name define its formula?','No. Obtain the actual component identities and commercial-grade information. Do not infer composition or a substitution ratio from an application name.'],['What should a comparison trial record?','Record the complete recipe, benchmark, water and salt conditions, mixing and heating sequence, and application-specific observations such as texture, separation or baking response.']],references:[]})
];
export const additionalPhosphateProducts = phosphateEntries.map(({procurement,...product})=>product);
export const additionalPhosphateProcurement = Object.fromEntries(phosphateEntries.map(p=>[p.slug,p.procurement]));
