import { productProcurement, focusProducts } from './product-procurement.mjs';
import { phosphateDetails } from './phosphate-details.mjs';

export function productIdentity(item,e){
  const data=productProcurement(item);
  return `<p class="product-identity">${e(data.identity)}</p><p class="product-names"><strong>Also known as:</strong> ${e([item.abbr,...data.aliases].join(' · '))}</p>`;
}

export function procurementSections(item,e,sectionHead){
  const data=productProcurement(item);
  return `<section class="page-section product-procurement"><div class="container">${sectionHead('GRADE & SPECIFICATION','Key parameters <span class="serif-accent">to confirm.</span>')}<p>${e(data.grade)}</p><p id="parameter-note">These are procurement questions, not a supplied specification. Units below indicate reporting context, not acceptance limits. Compare the current grade, source, document revision and test method before agreeing values.</p><p class="table-scroll-hint">If columns extend beyond the frame, scroll the table horizontally.</p><div class="parameter-table-wrap" tabindex="0" role="region" aria-label="${e(item.name)} parameter table" aria-describedby="parameter-note"><table class="parameter-table"><caption>Key parameters to confirm — ${e(item.name)}</caption><thead><tr><th scope="col">Parameter</th><th scope="col">What to request</th><th scope="col">Units or test context</th><th scope="col">Why it matters</th></tr></thead><tbody>${data.parameters.map(row=>`<tr><th scope="row">${e(row[0])}</th>${row.slice(1).map(cell=>`<td>${e(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${focusProducts.includes(item.slug)?`<div class="product-trial"><h3>${e(data.trialTitle)}</h3><p><strong>Describe the system:</strong> ${e(data.trialBrief)}</p><p><strong>Observe in a controlled trial:</strong> ${e(data.observations)}</p><p>A trial informs selection for that material and process; it is not a guarantee for a different grade or future batch.</p></div>`:''}</div></section>`;
}

export function productFaq(item,e,sectionHead){
  const data=productProcurement(item);
  return `<section class="page-section page-section--tint"><div class="container">${sectionHead('PURCHASING QUESTIONS',`${e(item.abbr)}: what to ask next.`)}<div class="product-faq">${data.faqs.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</div><div class="product-commercial"><h3>Packaging, handling & ordering</h3><p>${phosphateDetails[item.slug]?e(phosphateDetails[item.slug].handling):'Include volume, delivery destination and required timing in the inquiry. Ask about available pack formats, minimum order, sample terms and transport arrangements for the specific offer. Confirm storage instructions, shelf life and label details against the proposed source’s current records.'}</p>${phosphateDetails[item.slug]?'<p>Share your quantity and required delivery timing. Minimum order, sample terms, packing and the stated shelf life belong to the specific quotation and source records.</p>':''}</div>${data.references.length?`<div class="product-references"><h3>Identity reference points</h3><p>These sources support technical identity checks. They do not establish a supplied grade, source approval or permission in every food or market.</p><ul>${data.references.map(([label,url])=>`<li><a href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(label)}</a></li>`).join('')}</ul></div>`:''}</div></section>`;
}
