import { documentTypes, identityChecks, orderChecks } from './supply.mjs';
import { brand } from './brand.mjs';
import { inquiryUrl } from './journeys.mjs';
import { contactForm } from './contact-form.mjs';

export function documentRequestUrl({ingredient='',documents='',purpose='Supplier qualification',from='quality'}={}) {
 return inquiryUrl({intent:'documents',ingredient,documents,purpose,from});
}

export function supplyPages({e,banner,sectionHead,cta,returnRoutes}) {
  const request = values => e(documentRequestUrl(values));
  const quality = banner('QUALITY & SUPPLY','Product documents.<br><em>Clear purchasing requirements.</em>','Tell us the product, grade and destination market, together with the documents you need for your purchasing review.','Quality & Supply')+`<nav class="container family-links" aria-label="Qualification topics"><a href="#supply-identity">Supply identity</a><a href="#documents">Product documents</a><a href="#sample-review">Samples & specifications</a><a href="#certificate-scope">Certificate scope</a><a href="#order-conditions">Order conditions</a></nav>`+
    `<section class="page-section"><div class="container quality-intro"><div>${sectionHead('COMPANY CONTEXT','A clear starting point<br><span class="serif-accent">for qualification.</span>')}<p>${e(brand.established)} Our focus is phosphates, propionates, sorbates, sodium CMC and hydrocolloids. For a product inquiry, include your required grade, application and destination market.</p><p>Before ordering, agree the seller, producer, specification and supporting records for the proposed supply.</p><a class="text-link" href="../about/index.html">Company identity and background <span aria-hidden="true">↗</span></a></div><aside class="quality-callout"><span>BEFORE APPROVAL</span><ol><li>Named legal entity</li><li>Exact product and grade</li><li>Producer or packing site</li><li>Document scope and revision</li></ol></aside></div></section>`+
    `<section class="page-section page-section--tint" id="supply-identity"><div class="container">${sectionHead('01 / SUPPLY IDENTITY','Confirm who is involved.','Identify the seller, producer and relevant transaction roles in the quotation and order documents.')}<div class="supplier-check-grid">${identityChecks.map(([title,text])=>`<article><h3>${e(title)}</h3><p>${e(text)}</p></article>`).join('')}</div></div></section>`+
    `<section class="page-section" id="documents"><div class="container">${sectionHead('02 / DOCUMENT REVIEW','Ask for the record<br><span class="serif-accent">that answers your question.</span>','Tell us which records your purchasing or quality team needs. Document availability and sharing terms depend on the product and source.')}<div class="supplier-document-grid">${documentTypes.map(doc=>`<article id="document-${doc.id}"><span class="micro-label">${doc.short}</span><h3>${e(doc.label)}</h3><p>${e(doc.purpose)}</p><h4>What to check</h4><p>${e(doc.check)}</p><p class="supplier-boundary">${e(doc.boundary)}</p><a class="text-link" href="${request({documents:doc.request})}">Request ${doc.short==='DECL'?'a declaration':doc.short==='CERT'?'scope information':doc.short==='SPEC'?'a specification':doc.short} <span aria-hidden="true">↗</span></a></article>`).join('')}</div><p class="supplier-note">Include your application, destination market and review purpose so your request identifies the relevant records.</p><div class="quality-reading"><strong>Read the guides:</strong><a href="../knowledge/specification-tds-coa.html">Specification, TDS and COA <span aria-hidden="true">↗</span></a><a href="../knowledge/qualify-ingredient-source.html">Qualifying a new source <span aria-hidden="true">↗</span></a></div></div></section>`+
    `<section class="page-section page-section--tint" id="sample-review"><div class="container">${sectionHead('03 / SAMPLE & SPECIFICATION','Compare like with like.')}<ol class="quality-steps"><li><span>01</span><h3>Identity and revision</h3><p>Use the same material, grade and source when comparing the specification, TDS and COA. Record the versions reviewed.</p></li><li><span>02</span><h3>Method and conditions</h3><p>Compare units, preparation, concentration, temperature and analytical method where they affect the reported value.</p></li><li><span>03</span><h3>Limits and results</h3><p>Distinguish agreed acceptance limits from typical values and measured results for one sample or lot.</p></li><li><span>04</span><h3>Finished-food trial</h3><p>Evaluate the candidate in the intended food and process. Agree what sample results mean for qualification of the commercial supply.</p></li></ol></div></section>`+
    `<section class="page-section" id="certificate-scope"><div class="container quality-intro"><div>${sectionHead('04 / CERTIFICATE SCOPE','Review the certificate<br><span class="serif-accent">for the proposed source.</span>')}<p>Check the certificate holder, issuing body, activity or product scope, listed sites, dates and current status. A management-system certificate concerns the stated system and scope; it is not proof that every listed ingredient has separate product certification.</p><p>Halal, Kosher, allergen, GMO, origin, irradiation or traceability requirements can be included in your inquiry. Name the required standard or declaration and the product it needs to cover. Availability is source-specific.</p></div><aside class="quality-callout"><span>CERTIFICATION SCOPE</span><p>We do not claim certification for IngredientCore or its products. Bespring and other source certificates apply only to their named holders, sites and stated scope.</p><a href="${request({documents:'Applicable certificates and source-specific declarations; please confirm scope'})}">Ask about applicable records <span aria-hidden="true">↗</span></a></aside></div></section>`+
    `<section class="page-section page-section--tint" id="order-conditions"><div class="container">${sectionHead('05 / ORDER CONDITIONS','Agree the details<br><span class="serif-accent">before commitment.</span>','Include these details when discussing a sample, quotation or order with us.')}<div class="supplier-check-grid">${orderChecks.map(([title,text])=>`<article><h3>${e(title)}</h3><p>${e(text)}</p></article>`).join('')}</div></div></section>`+
    `<section class="page-section"><div class="container supplier-faq">${sectionHead('BUYER QUESTIONS','Useful answers before you ask.')}<details><summary>Are product documents available for immediate download?</summary><p>Please request documents by email, specifying the product, grade, destination market and required record. Availability and sharing permission depend on the proposed source.</p></details><details><summary>Which company details should appear in my quotation?</summary><p>Check the complete legal name of the contracting seller, the invoice issuer and the producer. Where relevant, also identify the exporter. These roles should be clear in the quotation and order records.</p></details><details><summary>Can a representative COA approve future batches?</summary><p>A representative COA helps you understand a record and initial results. Agree the specification, batch documentation and receiving criteria separately for commercial deliveries.</p></details><details><summary>Can I request a confidential file?</summary><p>Describe the record and why you need it without sending unnecessary confidential information. Sharing permission and a suitable delivery method must be agreed before a restricted file is provided.</p></details><a class="button button--navy" href="${request({documents:'Product qualification documents; please confirm availability'})}">Request product documents <span aria-hidden="true">↗</span></a></div></section>`;

  const sampleQuestion = `<section class="page-section"><div class="container quality-intro"><div>${sectionHead('SAMPLE QUESTION','Ask before planning a trial.')}<p>Tell us the material, grade, quantity and trial schedule you have in mind. Sample availability, source, dispatch terms and timing are agreed for each request.</p><a class="text-link" href="${e(inquiryUrl({intent:'sample',purpose:'Sample availability and proposed grade',from:'quality'}))}">Ask about sample availability <span aria-hidden="true">↗</span></a></div></div></section>`;

  const about = banner('ABOUT INGREDIENTCORE','A food ingredient subsidiary.<br><em>Established in 2025.</em>',brand.established,'About')+
    `<section class="page-section"><div class="container about-story"><div>${sectionHead('OUR COMPANY','IngredientCore.<br><span class="serif-accent">Focused on food ingredients.</span>')}</div><div><p class="about-story__lead">Founded in 2025, IngredientCore is a subsidiary of Bespring Chemical.</p><p>We focus on phosphates, propionates, sorbates, sodium CMC and hydrocolloids for food manufacturers and ingredient distributors.</p><p>Contact us with the ingredient or function you need, your food application and target specification. Include your destination market and document requirements to start a focused purchasing discussion.</p><a class="text-link" href="../quality/index.html#supply-identity">Product documents and purchasing details <span aria-hidden="true">↗</span></a></div></div></section>`+
    `<section class="page-section page-section--tint"><div class="container">${sectionHead('PARENT & SUBSIDIARY','Our company.<br><span class="serif-accent">Our parent’s background.</span>','We were established in 2025. Our parent, Bespring Chemical, describes its earlier phosphate business history in its company profile.')}<div class="timeline"><article><span>1970s</span><div><h3>Bespring’s phosphate roots</h3><p>Bespring’s company profile traces its background to the former Pizhou No. 2 Chemical Plant.</p></div></article><article><span>2014</span><div><h3>Bespring’s restructuring</h3><p>The parent’s profile identifies 2014 as the restructuring under the Bespring Chemical name.</p></div></article><article><span>2025</span><div><h3>IngredientCore established</h3><p>IngredientCore was established as a subsidiary of Bespring Chemical with a food ingredient focus.</p></div></article></div><p class="supplier-note">Learn more about our parent: <a href="https://www.bespringchem.com/about/company-profile.html" target="_blank" rel="noopener noreferrer">Bespring Chemical company profile <span aria-hidden="true">↗</span></a>.</p></div></section>`+
    `<section class="page-section"><div class="container">${sectionHead('A USEFUL FIRST CONVERSATION','Bring the context.<br><span class="serif-accent">Ask for the evidence.</span>')}<div class="principles"><article><span>01</span><h3>The food and function</h3><p>Describe the food, process and outcome you need. A chemical name alone may leave the grade or trial conditions unclear.</p></article><article><span>02</span><h3>The exact source</h3><p>Ask which producer, grade and site are being proposed. Qualification should follow the offer and its supporting records.</p></article><article><span>03</span><h3>The document scope</h3><p>Tell us which specifications, batch records or declarations your team needs, including the product and destination market they must cover.</p></article></div></div></section>`+
    cta('Start with the ingredient and market.','Include your application, target specification and document requirements.','Prepare inquiry',inquiryUrl({from:'about'}));

  const contact = banner('CONTACT INGREDIENTCORE','Tell us about<br><em>your ingredient requirements.</em>','Contact IngredientCore about a product, food application, specification or document request.','Contact')+
    `<section class="page-section"><div class="container contact-page"><div class="contact-page__intro"><div class="section-kicker"><span class="section-kicker__line"></span> INGREDIENT OR DOCUMENT INQUIRY</div><h2>Make the request<br><span class="serif-accent">specific.</span></h2><p>Tell us the product or target function, food application, specification, estimated quantity and destination market. For documents, include the grade and purpose of your review; availability depends on the product and source.</p><p>Use the form to prepare your email, or contact us directly using the details below.</p><p><a class="contact-guide-link" href="../quality/index.html#documents">Which document answers your question? <span aria-hidden="true">↗</span></a></p><div class="contact-details"><div><span>EMAIL</span><a href="mailto:${e(brand.email)}">${e(brand.email)}</a></div><div><span>PHONE</span><a href="tel:${e(brand.phone)}">${e(brand.phoneDisplay)}</a></div><div><span>CONTACT ADDRESS</span><address>${brand.addressLines.map(e).join('<br>')}</address></div></div></div>${contactForm(e,brand,returnRoutes)}</div></section>`+
    `<section class="page-section page-section--tint"><div class="container"><nav class="family-links" aria-label="Review before completing your inquiry"><a href="../products/index.html">Browse product requirements</a><a href="../applications/index.html">Review food applications</a><a href="../quality/index.html#documents">Understand product documents</a></nav>${sectionHead('FOR A DOCUMENT REQUEST','Five details to include.')}<div class="brief-grid"><span>01 / Product and grade</span><span>02 / Food application</span><span>03 / Destination market</span><span>04 / Required records</span><span>05 / Purpose of review</span></div><p class="supplier-note"><a href="../knowledge/write-ingredient-brief.html">Read the ingredient brief guide <span aria-hidden="true">↗</span></a></p></div></section>`;

  return [
    {path:'quality/index.html',title:'Food Ingredient Documents & Supply Review',description:'Review seller and producer identity, proposed grade, specification, batch COA and certificate scope before a food ingredient purchase.',active:'Quality & Supply',body:quality+sampleQuestion},
    {path:'about/index.html',title:'About IngredientCore',description:'IngredientCore was established in 2025 as a Bespring Chemical subsidiary. Explore our food ingredient focus and our parent company’s background.',active:'About',body:about},
    {path:'contact/index.html',title:'Contact IngredientCore About an Ingredient',description:'Prepare an email inquiry with product, grade, food application, destination market and documents needed. No information is sent until you use your mail app.',active:'Contact',body:contact}
  ];
}
