import {sourceRecord} from './technical-sources.mjs';
export function comparisonTable(table,e){
 return `<p class="table-scroll-hint">If columns extend beyond the frame, scroll the table horizontally.</p><div class="parameter-table-wrap technical-table-wrap" role="region" tabindex="0" aria-label="${e(table.caption)}"><table class="parameter-table technical-table"><caption>${e(table.caption)}</caption><thead><tr>${table.headers.map(h=>`<th scope="col">${e(h)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(row=>`<tr><th scope="row">${e(row[0])}</th>${row.slice(1).map(cell=>`<td>${e(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
export function sourceLinks(ids,e){return `<p class="technical-citations"><strong>Technical basis:</strong> ${ids.map(id=>{const s=sourceRecord(id);return `<a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.label)}</a>`;}).join(' · ')}</p>`;}
export function sourcesWithScope(ids,e){return `<ul class="technical-source-list">${ids.map(id=>{const s=sourceRecord(id);return `<li><a href="${e(s.url)}" target="_blank" rel="noopener noreferrer">${e(s.label)}</a><p>${e(s.scope)}</p></li>`;}).join('')}</ul>`;}
export function applicationContent(item,{e,products,articles,productLink,applicationGoals,applicationInquiry}){
 const familyCounts=new Map();for(const slug of item.links){const family=products.find(p=>p.slug===slug).family;familyCounts.set(family,(familyCounts.get(family)||0)+1);}
 const familyRoutes=[...familyCounts].filter(([,count])=>count>1).map(([family])=>`<a href="../products/index.html#${family.toLowerCase().replace(/[^a-z0-9]+/g,'-')}">Browse ${e(family)}</a>`).join('');
 const matrix={caption:`${item.name}: problems, candidate directions and observations`,headers:['Problem','Candidate direction','Key conditions','Validation direction'],rows:item.matrix};
 return `<article id="${e(item.id)}" class="application-row"><div class="application-row__title"><span>${e(item.number)} / APPLICATION</span><h3>${e(item.name)}</h3><p>${e(item.intro)}</p><p class="application-goal"><strong>Target functions:</strong> ${e(applicationGoals[item.id])}</p><a class="button button--navy application-inquiry" href="${e(applicationInquiry(item))}">Prepare application inquiry <span aria-hidden="true">↗</span></a></div><div class="application-row__detail"><div class="application-systems">${item.systems.map(([name,body])=>`<section><h4>${e(name)}</h4><p>${e(body)}</p></section>`).join('')}</div><h4>Define the conditions first</h4><ul>${item.questions.map(q=>`<li>${e(q)}</li>`).join('')}</ul>${comparisonTable(matrix,e)}<p class="application-boundary">Select the grade for your food and process, and check permitted uses in your destination market.</p><h4>Prepare an initial comparison</h4><ul>${item.trial.map(p=>`<li>${e(p)}</li>`).join('')}</ul><h4>Records to ask about</h4><ul>${item.documents.map(p=>`<li>${e(p)}</li>`).join('')}</ul><p>Tell us which records you need for the proposed material. Availability and sharing terms depend on its source.</p><div class="application-brief"><h4>Include in this application inquiry</h4><ul>${item.brief.map(p=>`<li>${e(p)}</li>`).join('')}</ul><a class="button button--navy application-inquiry" href="${e(applicationInquiry(item))}">Prepare application inquiry <span aria-hidden="true">↗</span></a></div><div class="application-row__links"><strong>Ingredient guides to review</strong>${item.links.map(slug=>{const p=products.find(x=>x.slug===slug);if(!p)throw new Error('Unknown application product '+slug);return productLink(slug,p.name).replace('.html"',`.html?${new URLSearchParams({application:item.name,goal:applicationGoals[item.id]}).toString().replaceAll('&','&amp;')}"`);}).join('')}</div>${familyRoutes?`<div class="application-row__reading"><strong>Browse the related families</strong>${familyRoutes}</div>`:''}<div class="application-row__reading"><strong>Next reading</strong>${item.readings.map(slug=>{const a=articles.find(x=>x.slug===slug);if(!a)throw new Error('Unknown application reading '+slug);return `<a href="../knowledge/${e(slug)}.html">${e(a.title)} <span aria-hidden="true">↗</span></a>`;}).join('')}</div><details class="application-evidence"><summary>Sources and their scope</summary>${sourcesWithScope(item.sources,e)}</details></div></article>`;
}
