// Primary sources and explicit boundaries. No supplier relationship is implied.
export const technicalSources={
 modifiedStarch:{label:'FAO/JECFA — Modified starches (2014)',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/monograph16/additive-287-m16.pdf',scope:'Starch modification routes and finished-starch identity requirements; not a production recipe or permission to add STMP directly to finished foods.'},
 mapIdentity:{label:'FAO/JECFA — Ammonium dihydrogen phosphate',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-023.pdf',scope:'MAP identity and acid-base characteristics; not evidence of performance in a fermentation medium.'},
 dapIdentity:{label:'FAO/JECFA — Diammonium hydrogen phosphate',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-150-m1-corr.pdf',scope:'DAP identity and listed yeast-food function; no dose or fermentation outcome is transferred to supplied material.'},
 mkpIdentity:{label:'FAO/JECFA — Potassium dihydrogen phosphate',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-336.pdf',scope:'MKP identity and composition; not validation of a particular nutrient medium.'},
 dcpIdentity:{label:'FAO/JECFA — Calcium hydrogen phosphate',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-085.pdf',scope:'Anhydrous/dihydrate identity distinction; not a source-specific particle or performance specification.'},
 tcpIdentity:{label:'FAO/JECFA — Tricalcium phosphate',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-475.pdf',scope:'Commercial composition, solubility and listed anticaking/buffer functions; not a finished-food result or nutrition claim.'},
 stpp:{label:'FAO JECFA — Pentasodium Triphosphate',url:'https://www.fao.org/food/food-safety-quality/scientific-advice/jecfa/jecfa-additives/detail/en/c/406/',scope:'Identity reference; not an offered grade or a market-use authorization.'},
 shmp:{label:'FAO JECFA — Sodium Polyphosphate, glassy',url:'https://www.fao.org/food/food-safety-quality/scientific-advice/jecfa/jecfa-additives/detail/en/c/299/',scope:'Commercial identity reference; not a source specification or reaction/performance result.'},
 sapp:{label:'FAO JECFA — Disodium Pyrophosphate',url:'https://www.fao.org/food/food-safety-quality/scientific-advice/jecfa/jecfa-additives/details-simple/en/?ins_id=450%28i%29',scope:'Identity and synonyms; a chemical entry does not define a reaction-rate grade.'},
 salp:{label:'FAO JECFA — Sodium Aluminium Phosphate, Acidic',url:'https://www.fao.org/fileadmin/user_upload/jecfa_additives/docs/Monograph1/Additive-389.pdf',scope:'Acidic material identity in the cited monograph; not all materials called SALP or current local permission.'},
 cmc:{label:'WHO JECFA — Sodium Carboxymethyl Cellulose',url:'https://apps.who.int/food-additives-contaminants-jecfa-database/Home/Chemical/3773',scope:'Names and material identity; not a viscosity grade or a supplied specification.'},
 leavening:{label:'ICL — Leavening: It’s a Simple Equation (2025)',url:'https://www.iclfood.com/wp-content/uploads/2025/02/ICL25-LeaveningWhitePaper.pdf',scope:'Producer technical explanation of acid–bicarbonate balance and model dough reaction tests. Its grades and curves do not describe IngredientCore supply.'},
 beef:{label:'Original study — Phosphates in buffalo meat and patties (1989)',url:'https://pubmed.ncbi.nlm.nih.gov/22054678/',scope:'Original study abstract: specified meat, salt and phosphate treatments. No ranking, dose or improvement figure is transferred to other foods or supplied grades.'},
 waffle:{label:'Original study — Waffle batter and leavening study (2017)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC5448353/',scope:'A fresh-egg waffle system; supports recording batter/line variables, not a universal SAPP/SALP substitution rule.'},
 preservation:{label:'Original study — Preservative comparisons in media and animal products (2023)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9998193/',scope:'Specific organisms, laboratory media and selected foods. Inhibition results are not finished-food use levels, safety limits or shelf-life guarantees.'},
 hygiene:{label:'FAO — Good Hygiene Practices and control of food hazards (2023)',url:'https://www.fao.org/good-hygiene-practices-haccp-toolbox/ghp/introduction-to-ghp/',scope:'Food-hygiene foundation based on Codex principles; not a claim about IngredientCore’s implemented system.'},
 carrageenan:{label:'FAO — A Guide to the Seaweed Industry, Carrageenan (2003)',url:'https://www.fao.org/4/y4765e/y4765e0a.htm',scope:'Technical distinctions between carrageenan types and ionic gel behavior; not a current grade specification or permission decision.'},
 milkTea:{label:'Original study — Stabilizer screening in milk tea (2023)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10094277/',scope:'The tested tea/milk system and stabilizer combinations; not evidence that one gum suits every dairy or plant-based drink.'},
 soy:{label:'Original study — CMC in a soy-protein/rice-bran-oil model emulsion (2022)',url:'https://www.frontiersin.org/journals/nutrition/articles/10.3389/fnut.2022.878725/full',scope:'A model emulsion under specified preparation and acidic conditions, with laboratory reagents. No recipe, dose or ready-to-use food process is reproduced.'},
 acidity:{label:'FDA-hosted IFT report — pH, buffering and titratable acidity',url:'https://www.fda.gov/media/103613/download',scope:'Chapter 3 technical definitions in a historical report. Not current market permission, process approval or a safe-pH threshold.'},
 sourness:{label:'Original study — Perception of citric acid/citrate mixtures (2025)',url:'https://pubmed.ncbi.nlm.nih.gov/40481661/',scope:'Human sensory experiments in aqueous mixtures. Their findings do not predict taste or stability in every finished food.'},
 waterActivity:{label:'FDA — Water Activity (aw) in Foods',url:'https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/inspection-technical-guides/water-activity-aw-foods',scope:'Technical measurement context; no regulatory threshold or safe-food conclusion is inferred here.'},
 sds:{label:'OSHA — Hazard Communication: Safety Data Sheets',url:'https://www.osha.gov/Publications/OSHA3514.html',scope:'US hazard-communication context; an SDS is not a food-grade certificate or batch acceptance report.'},
 iso:{label:'ISO — Certification',url:'https://www.iso.org/certification.html',scope:'Certification and independent issuing bodies; not verification of any company’s certificate or its coverage.'},
 supply:{label:'FDA — Preventive Controls for Human Food, supply-chain program',url:'https://www.fda.gov/food/food-safety-modernization-act-fsma/fsma-final-rule-preventive-controls-human-food',scope:'Risk-based US framework when applicable. Check applicability to the buyer’s activities and food category; this reference does not establish product approval.'}
};
export function sourceRecord(id){const source=technicalSources[id];if(!source)throw new Error('Unknown technical source '+id);return source;}
export const sourceTuples=ids=>ids.map(id=>{const s=sourceRecord(id);return [s.label,s.url,s.scope];});
